-- Align shared 34-team catalog across Y Factor, Alfredo, and live Supabase. (auto-generated)
-- Source: poke-sim/data.js TEAMS literal and poke-sim/tools/generate_seed_from_data.py
-- Preferred live-DB catalog alignment path. Re-run the generator instead of editing by hand.
-- Safe shape: transaction + ruleset/team UPSERTs + team_members replace for canonical team IDs only.
-- No schema changes. No secrets. No destructive delete from teams/rulesets.

BEGIN;

INSERT INTO rulesets (ruleset_id, format_group, engine_formatid, description, custom_rules)
VALUES (
  'champions_reg_m_doubles_bo3',
  'Champion',
  'gen9championsvgc2026regma',
  'Champions 2026 Reg M A — Doubles, bring 6 pick 4, level 50, Bo3',
  '{"bring":6,"choose":4,"gameMode":"doubles","levelCap":50}'::jsonb
)
ON CONFLICT (ruleset_id) DO UPDATE SET
  format_group = EXCLUDED.format_group,
  engine_formatid = EXCLUDED.engine_formatid,
  description = EXCLUDED.description,
  custom_rules = EXCLUDED.custom_rules;

INSERT INTO teams (team_id, name, label, mode, ruleset_id, source, source_ref, description, metadata)
VALUES
  ('player', 'TR Counter Squad', 'YOUR TEAM', 'player', 'champions_reg_m_doubles_bo3', 'builtin', 'player_champions_speed_v1', 'Fast offensive pressure with Intimidate + Will-O-Wisp support. Built to break Trick Room before it starts.', '{"assumption_register":["This remains a user-authored starter team, not a pinned event export.","The original anti-Trick-Room shell was preserved while converting its spreads to Champions SP scale."],"champion_pack_id":"player_champions_speed_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champion testing anti-Trick-Room starter. Moves, items, and Champions SP spreads are pinned to the current Showdown-backed legality gate; this is not an exact tournament export.","legality_status":"legal","provenance":{"author":"user","roster_source":"user-authored","spread_source":"user-authored","status":"testing_archetype","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"speed"}'::jsonb),
  ('mega_altaria', 'Mega Altaria', 'HYBRID RAINBOW', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'mega_altaria_champions_regma_v1', 'Sun-rain hybrid with Trick Room threat via Sinistcha. Prankster Whimsicott provides flexible speed control.', '{"assumption_register":[],"champion_pack_id":"mega_altaria_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Remove invented gen9championsvgc2026regma tag in T10.","legality_status":"legal","provenance":{"author":"community","roster_source":"https://pokepast.es/dfdfa66d317cf9d7","spread_source":"https://pokepast.es/dfdfa66d317cf9d7","status":"exact","url":"https://pokepast.es/dfdfa66d317cf9d7"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"weather_support"}'::jsonb),
  ('mega_dragonite', 'Mega Dragonite', 'HYBRID RAINBOW', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'mega_dragonite_champions_regma_v1', 'Rain team with Mega Dragonite as the primary sweeper. Basculegion Adaptability + Archaludon Electro Shot under rain.', '{"assumption_register":["Dragonite Mega form verified via Game8 Items List and Victory Road Reg M-A docs.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"mega_dragonite_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Dragonite is a new Champions-introduced Mega Evolution (Dragoninite, Shop: 2000 VP). Legal in Reg M-A. Source: Game8 Items List; Victory Road Reg M-A.","legality_status":"legal","provenance":{"author":"community","roster_source":"https://pokepast.es/dd101585183c9ed6","spread_source":"https://pokepast.es/dd101585183c9ed6","status":"unproven","url":"https://pokepast.es/dd101585183c9ed6"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"rain"}'::jsonb),
  ('mega_houndoom', 'Mega Houndoom', 'HYBRID RAINBOW', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'mega_houndoom_champions_regma_v1', 'Sun + Trick Room hybrid. Mega Houndoom Solar Power nukes under sun. Flexible TR setters in Sinistcha, Farigiraf, Whimsicott.', '{"assumption_register":["Team carries two Mega Stones; only one activation per match per Reg M-A rules.","Item Clause satisfied: Houndoominite and Drampanite are distinct items.","Drampa Mega form verified via Game8 Items List."],"champion_pack_id":"mega_houndoom_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Houndoom (Houndoominite, Gen 6 classic) plus secondary Drampa with Drampanite (new Champions Mega). Both Mega Stones legal; only one can activate per match per Reg M-A rules. Item Clause satisfied: Houndoominite != Drampanite.","legality_status":"legal","provenance":{"author":"community","roster_source":"https://pokepast.es/4a87b07998f6c0c4","spread_source":"https://pokepast.es/4a87b07998f6c0c4","status":"unproven","url":"https://pokepast.es/4a87b07998f6c0c4"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sun_tr"}'::jsonb),
  ('rin_sand', 'Rin Sand', 'RIN', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'rin_sand_champions_regma_v1', 'Sand offense with Tyranitar + Excadrill core. Sneasler Unburden for burst speed. Dragapult for speed and spread.', '{"assumption_register":["Meganium Mega form verified via Game8 Items List.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"rin_sand_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Meganium is a new Champions-introduced Mega Evolution (Meganiumite, Shop: 2000 VP or Battle Pass M-1 reward). Legal in Reg M-A. Source: Game8 Items List.","legality_status":"legal","provenance":{"author":"community","roster_source":"https://pokepast.es/e97ac67f1ce79c33","spread_source":"https://pokepast.es/e97ac67f1ce79c33","status":"unproven","url":"https://pokepast.es/e97ac67f1ce79c33"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sand"}'::jsonb),
  ('suica_sun', 'Suica Sun', 'SUICA', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'suica_sun_champions_regma_v1', 'Charizard Y sun offense. Sneasler + Basculegion revenge killers. Incineroar provides Intimidate support.', '{"assumption_register":["2026-05-24 audit: Sinistcha item was recorded as Kouba Berry from the public P08QQ5NU9C rental mirror after a repo transcription error duplicated Sitrus Berry.","2026-06-21 Champion item-pool gate: Kouba Berry is not in the verified Champions item list, so the shipped sim uses Coba Berry until a stronger source proves otherwise."],"champion_pack_id":"suica_sun_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champion sun testing archetype adjusted from the linked paste so all moves pass the current Showdown-backed species/form legality gate.","legality_status":"legal","provenance":{"author":"community","roster_source":"https://pokepast.es/cb48d8b06c73d33b","spread_source":"https://pokepast.es/cb48d8b06c73d33b","status":"testing_archetype_adjusted","url":"https://pokepast.es/cb48d8b06c73d33b"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sun"}'::jsonb),
  ('cofagrigus_tr', 'Cofagrigus TR', 'TRICK ROOM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'cofagrigus_tr_champions_regma_v1', 'Classic Trick Room team. Cofagrigus + Sinistcha lead sets TR. Slow, powerful sweepers underneath.', '{"assumption_register":["Spreads inferred from meta norms, not a pinned paste."],"champion_pack_id":"cofagrigus_tr_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champion Trick Room testing archetype. Team passes the current Champions SP, item, and Showdown-backed move legality gates while preserving the slow-room identity.","legality_status":"legal","provenance":{"author":"community","roster_source":"community","spread_source":"community","status":"testing_archetype","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"trick_room"}'::jsonb),
  ('champions_arena_1st', 'Hyungwoo Shin — Champions Arena', '1ST CHAMPIONS ARENA', 'champion_pack', 'champions_reg_m_doubles_bo3', 'builtin', 'champions_arena_1st_v1', 'Mega Charizard-Y Sun with Coil Milotic secret weapon. Champions Arena winner April 2026. Rental: SQMPYRW6BP', '{"assumption_register":["2026-06-23 legality repair: Milotic Hypnosis, Incineroar Parting Shot, and Sneasler Fake Out were replaced for current generated legality.","Original source remains linked for review, but this shipped row is an adjusted testing archetype."],"champion_pack_id":"champions_arena_1st_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champion sun testing archetype adjusted from Champions Arena coverage so all moves pass the current Showdown-backed species/form legality gate; do not treat as an exact tournament paste.","legality_status":"legal","provenance":{"author":"Hyungwoo Shin","roster_source":"Victory Road Champions Arena coverage","spread_source":"Victory Road Champions Arena coverage","status":"testing_archetype_adjusted","url":"https://victoryroad.pro/champions-regulations/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sun"}'::jsonb),
  ('champions_arena_2nd', 'Jorge Tabuyo — Champions Arena Finalist', '2ND CHAMPIONS ARENA', 'champion_pack', 'champions_reg_m_doubles_bo3', 'builtin', 'champions_arena_2nd_v1', 'Double Mega Charizard-X + Tyranitar with Sinistcha TR fallback. Rental: P08QQ5NU9C', '{"assumption_register":["2026-06-23 legality repair: Incineroar Parting Shot and Sneasler Fake Out were replaced for current generated legality.","Original source remains linked for review, but this shipped row is an adjusted testing archetype."],"champion_pack_id":"champions_arena_2nd_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champion balance/setup testing archetype adjusted from Champions Arena coverage so all moves pass the current Showdown-backed species/form legality gate; do not treat as an exact tournament paste.","legality_status":"legal","provenance":{"author":"Jorge Tabuyo","roster_source":"Victory Road Champions Arena coverage","spread_source":"Victory Road Champions Arena coverage","status":"testing_archetype_adjusted","url":"https://victoryroad.pro/champions-regulations/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"balance"}'::jsonb),
  ('champions_arena_3rd', 'Juan Benítez — Champions Arena Top 3', '3RD CHAMPIONS ARENA', 'champion_pack', 'champions_reg_m_doubles_bo3', 'builtin', 'champions_arena_3rd_v1', 'Mega Charizard-Y + Max Speed Kingambit tech. Prankster Whimsicott + Scarf Garchomp. Rental: KN6SNLGUPA', '{"assumption_register":[],"champion_pack_id":"champions_arena_3rd_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champions Arena Top 3.","legality_status":"legal","provenance":{"author":"Juan Benitez","roster_source":"Victory Road Champions Arena coverage","spread_source":"Victory Road Champions Arena coverage","status":"exact","url":"https://victoryroad.pro/champions-regulations/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sun"}'::jsonb),
  ('aurora_veil_froslass', 'Mega Froslass — Aurora Veil', 'VEIL TEAM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'aurora_veil_froslass_champions_regma_v1', 'Mega Froslass Snow Warning sets instant Aurora Veil. Dragonite + Kingambit behind veil. High win-condition team.', '{"assumption_register":["Froslass Mega form verified via Game8 Items List.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"aurora_veil_froslass_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Champion snow and Aurora Veil testing archetype. Team passes the current Champions SP, item, and Showdown-backed move legality gates while preserving the veil/setup identity.","legality_status":"legal","provenance":{"author":"community","roster_source":"community","spread_source":"community","status":"testing_archetype","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"veil"}'::jsonb),
  ('custom_1776995210260', 'Froslass''s Team', 'CUSTOM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', NULL, 'Imported via Showdown paste', '{"style":"custom"}'::jsonb),
  ('perish_trap_gengar', 'Perish Trap — Mega Gengar', 'PERISH TRAP', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'perish_trap_gengar_champions_regma_v1', 'Mega Gengar Shadow Tag + Perish Song trap core. Sinistcha Rage Powder redirection stalls opponents through perish countdown. Francesco Rasini Champions Arena Top 12.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"perish_trap_gengar_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Gengar legal in Reg M-A via Gengarite. Shadow Tag + Perish Song legal. Source: Pikalytics + VR Pastes.","legality_status":"legal_inferred","origin":{"event":"The Champions Arena (Rank #12)","player":"Francesco Rasini","url":"https://www.vrpastes.com/s8hEJH9u"},"provenance":{"author":"Francesco Rasini","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://www.vrpastes.com/s8hEJH9u"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"perish_trap"}'::jsonb),
  ('rain_offense', 'Rain Offense — Mega Meganium', 'RAIN', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'rain_offense_meganium_champions_regma_v1', 'Pelipper Drizzle + Basculegion Adaptability Wave Crash + Archaludon Electro Shot rain core. Mega Meganium (Mega Sol) secondary. leoscerni LIGA DA COMUNIDADE #2 Rank #3.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"rain_offense_meganium_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Meganium (new Champions Mega, Meganiumite) legal in Reg M-A. All other species standard. Source: Pikalytics Top Teams.","legality_status":"legal_inferred","origin":{"event":"LIGA DA COMUNIDADE #2 (Rank #3)","player":"leoscerni","url":"https://play.limitlesstcg.com/tournament/69d18b350e548b5c2fbe3486/player/leoscerni/teamlist"},"provenance":{"author":"leoscerni","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://play.limitlesstcg.com/tournament/69d18b350e548b5c2fbe3486/player/leoscerni/teamlist"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"rain_offense"}'::jsonb),
  ('trick_room_golurk', 'Trick Room — Mega Golurk', 'TRICK ROOM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'trick_room_golurk_champions_regma_v1', 'Farigiraf Armor Tail + Trick Room setter, Mega Golurk Iron Fist Headlong Rush sweeper, Torkoal Eruption cleanup. pokefey Torneo Salida Rank #2.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"trick_room_golurk_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Golurk legal in Reg M-A via Golurkite. Unseen Fist ability is updated in Champions (25% Protect bypass). Source: Pikalytics Top Teams.","legality_status":"legal_inferred","origin":{"event":"Torneo Salida Pokemon Champions (Rank #2)","player":"pokefey","url":"https://play.limitlesstcg.com/tournament/69d3c3270e548b5c2fbe4826/player/pokefey/teamlist"},"provenance":{"author":"pokefey","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://play.limitlesstcg.com/tournament/69d3c3270e548b5c2fbe4826/player/pokefey/teamlist"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"trick_room"}'::jsonb),
  ('sun_offense_charizard', 'Sun Offense — Mega Charizard Y', 'SUN', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'sun_offense_charizard_champions_regma_v1', 'Mega Charizard Y Drought + Torkoal Eruption + Hatterene/Farigiraf Trick Room hybrid. Jiang Jin-Hao Champions Arena Top 5.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"sun_offense_charizard_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Charizard Y legal in Reg M-A. Standard sun core + TR fallback. Source: Pikalytics + VR Pastes.","legality_status":"legal_inferred","origin":{"event":"The Champions Arena (Rank #5)","player":"Jiang Jin-Hao","url":"https://www.vrpastes.com/y1F6tzNe"},"provenance":{"author":"Jiang Jin-Hao","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://www.vrpastes.com/y1F6tzNe"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"sun_offense"}'::jsonb),
  ('z2r_feitosa_mega_floette', 'Z2R Feitosa — Mega Floette Balance', 'CHAMPIONS CUP', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'z2r_feitosa_champions_regma_v1', 'Mega Floette Fairy Aura Light of Ruin + Talonflame Gale Wings Tailwind + Basculegion/Kingambit dual wincon. Z2R Feitosa LIGA DA COMUNIDADE #2 Rank #2 15-0-0.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"z2r_feitosa_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Floette (Eternal Flower) requires HOME transfer — flagged by legality module. Floettite new Champions Mega. Source: Pikalytics Top Teams.","legality_status":"legal_inferred","origin":{"event":"LIGA DA COMUNIDADE #2 (Rank #2, 15-0-0)","player":"Z2R Feitosa","url":"https://play.limitlesstcg.com/tournament/69d18b350e548b5c2fbe3486/player/pedrohenriq/teamlist"},"provenance":{"author":"Z2R Feitosa","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://play.limitlesstcg.com/tournament/69d18b350e548b5c2fbe3486/player/pedrohenriq/teamlist"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"balance_mega"}'::jsonb),
  ('benny_v_mega_froslass', 'Benny V — Mega Froslass Wide League', 'WIDE LEAGUE', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'benny_v_champions_regma_v1', 'Mega Froslass Snow Cloak Blizzard + Basculegion Choice Scarf Last Respects + Kingambit closer. Benny V Wide League SNR #84 Rank #2 13-1-0.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"benny_v_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Froslass legal in Reg M-A via Froslassite. Standard Scarf + priority core. Source: Pikalytics Top Teams.","legality_status":"legal_inferred","origin":{"event":"Wide League SNR #84 (Rank #2, 13-1-0)","player":"Benny V","url":"https://play.limitlesstcg.com/tournament/69d7114dc734cfa1af2b581d/player/ginger78/teamlist"},"provenance":{"author":"Benny V","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://play.limitlesstcg.com/tournament/69d7114dc734cfa1af2b581d/player/ginger78/teamlist"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"snow_mega"}'::jsonb),
  ('lukasjoel1_sand_gengar', 'lukasjoel1 — Sand + Mega Gengar ZGG', 'ZGG CUP', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'lukasjoel1_champions_regma_v1', 'Tyranitar Sand Stream + Garchomp Sand Veil + Mega Gengar Shadow Tag trap core. lukasjoel1 ZGG #1 $200 Rank #2 13-2-0.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"lukasjoel1_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Gengar legal in Reg M-A via Gengarite. Shadow Tag + sand core. Source: Pikalytics Top Teams.","legality_status":"legal_inferred","origin":{"event":"ZGG #1 Pokemon Champions VGC $200 (Rank #2, 13-2-0)","player":"lukasjoel1","url":"https://play.limitlesstcg.com/tournament/69c44a46d478313a15a329c7/player/lukasjoel1/teamlist"},"provenance":{"author":"lukasjoel1","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://play.limitlesstcg.com/tournament/69c44a46d478313a15a329c7/player/lukasjoel1/teamlist"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"sand_trap"}'::jsonb),
  ('hiroto_imai_snow', 'Hiroto Imai — Snow + Mega Lopunny', 'CHAMPIONS CUP', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'hiroto_imai_snow_champions_regma_v1', 'Vanilluxe Snow Warning + Choice Scarf Blizzard spam, Mega Lopunny Fake Out disruption, Aegislash Stance Change. Hiroto Imai Champions Arena Rank #75.', '{"assumption_register":["Roster (species/items/abilities/moves) verified from open team list.","EVs, natures, and Tera types not disclosed by source; archetype-default spreads applied.","Mega activation consumes team''s once-per-match Mega slot."],"champion_pack_id":"hiroto_imai_snow_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Mega Lopunny legal in Reg M-A via Lopunnite. Vanilluxe Snow Warning standard. Source: Pikalytics + VR Pastes.","legality_status":"legal_inferred","origin":{"event":"The Champions Arena (Rank #75, 9-3)","player":"Hiroto Imai","url":"https://vrpastes.com/htQ0opai"},"provenance":{"author":"Hiroto Imai","roster_source":"pikalytics_top_teams","spread_source":"archetype_default","status":"roster-verified-spreads-inferred","url":"https://vrpastes.com/htQ0opai"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"snow_offense"}'::jsonb),
  ('fedecampovgc_aerodactyl_ariados', 'FedeCampoVGC — Aerodactyl Ariados', 'MAY META', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'fedecampovgc_aerodactyl_ariados_may2026_v1', 'Current May 2026 public meta-index roster built around Mega Aerodactyl + Mega Charizard Y pressure. Rental: AV7NTVGB10.', '{"assumption_register":["Species/forms verified from the public May 1, 2026 Champions meta index entry.","Items, abilities, moves, EVs, natures, and Tera types were inferred from current Reg M-A archetypes.","Team carries two Mega-capable species; actual per-game Mega choice remains player-selected in battle."],"champion_pack_id":"fedecampovgc_aerodactyl_ariados_may2026_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Species/forms verified from the current public Champions meta index. Full sets are inferred because the index does not expose a raw export in-repo.","legality_status":"legal_inferred","origin":{"event":"Public meta index (May 1, 2026) · rental AV7NTVGB10","player":"Federico Camporesi","url":"https://pokemonchampionsmeta.net/"},"provenance":{"author":"Federico Camporesi","roster_source":"pokemon_champions_meta_index","spread_source":"archetype_default","status":"species-forms-verified-sets-inferred","url":"https://pokemonchampionsmeta.net/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"speed_sun_pressure"}'::jsonb),
  ('swirlingroses_meganium_vivillon', 'swirlingroses — Meganium Vivillon Balance', 'MAY REPLAY', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'swirlingroses_meganium_vivillon_may2026_v1', 'May 6, 2026 Champions replay-preview roster with Sneasler / Basculegion / Incineroar / Kingambit / Meganium / Vivillon-Continental.', '{"assumption_register":["Only the six species were verified from the replay preview.","Items, abilities, moves, EVs, natures, and Tera types were inferred from current Reg M-A archetypes.","Vivillon-Continental uses Vivillon''s canonical statline and typing; regional wing pattern is cosmetic for sim purposes."],"champion_pack_id":"swirlingroses_meganium_vivillon_may2026_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Six species verified from the replay preview team line. Full sets are inferred because replay preview does not expose items, moves, or spreads.","legality_status":"legal_inferred","origin":{"event":"Pokémon Showdown replay preview (Tournament battle, May 6, 2026)","player":"swirlingroses","url":"https://replay.pokemonshowdown.com/gen9championsvgc2026regma-2603247306"},"provenance":{"author":"swirlingroses","roster_source":"pokemon_showdown_replay_preview","spread_source":"archetype_default","status":"species-verified-sets-inferred","url":"https://replay.pokemonshowdown.com/gen9championsvgc2026regma-2603247306"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"balance_speed"}'::jsonb),
  ('prro_t_floette_aerodactyl', 'Prro-T — Floette Aerodactyl Pressure', 'MAY REPLAY', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'prro_t_floette_aerodactyl_may2026_v1', 'May 8, 2026 Champions Bo3 replay-preview roster with Floette-Eternal / Aerodactyl / Incineroar / Garchomp / Sneasler / Basculegion.', '{"assumption_register":["Only the six species were verified from the replay preview.","Repo canonical naming normalizes replay-preview Floette-Eternal to Floette (Eternal Flower).","Items, abilities, moves, EVs, natures, and Tera types were inferred from current Reg M-A archetypes."],"champion_pack_id":"prro_t_floette_aerodactyl_may2026_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Six species verified from the replay preview team line. Full sets are inferred because replay preview does not expose items, moves, or spreads.","legality_status":"legal_inferred","origin":{"event":"Pokémon Showdown replay preview (Bo3 Game 2, May 8, 2026)","player":"Prro-T","url":"https://replay.pokemonshowdown.com/gen9championsvgc2026regma-2604413910"},"provenance":{"author":"Prro-T","roster_source":"pokemon_showdown_replay_preview","spread_source":"archetype_default","status":"species-verified-sets-inferred","url":"https://replay.pokemonshowdown.com/gen9championsvgc2026regma-2604413910"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"fast_pressure"}'::jsonb),
  ('fabulous_sunroom', 'Fabulous Sunroom', 'SAMPLE TEAM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'fabulous_sunroom_champions_regma_v1', 'Calibration sunroom built from public sample-team archetypes and shipped legal catalog sets.', '{"assumption_register":["Roster was assembled from already-shipped legal sets to widen calibration coverage.","This is a calibration shell, not a pinned public paste."],"champion_pack_id":"fabulous_sunroom_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Derived sample shell repaired to Champions Reg M-A legality by replacing the banned Arcanine Life Orb slot with a legal berry item while preserving the same sunroom structure.","legality_status":"legal_inferred","provenance":{"author":"calibration","roster_source":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/","spread_source":"archetype-derived from shipped catalog","status":"derived","url":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sun"}'::jsonb),
  ('sand_bulky_offense', 'Sand Bulky Offense', 'SAMPLE TEAM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'sand_bulky_offense_champions_regma_v1', 'Calibration sand offense built from shipped legal catalog sets and public sample-team archetypes.', '{"assumption_register":["Roster was assembled from already-shipped legal sets to widen calibration coverage.","This is a calibration shell, not a pinned public paste."],"champion_pack_id":"sand_bulky_offense_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Derived sample shell repaired to Champions Reg M-A legality by replacing the banned Gholdengo Choice Specs slot with a legal held item while preserving the same sand-offense role mix.","legality_status":"legal_inferred","provenance":{"author":"calibration","roster_source":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/","spread_source":"archetype-derived from shipped catalog","status":"derived","url":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"sand"}'::jsonb),
  ('fire_ice_fullroom', 'Fire and Ice Fullroom', 'SAMPLE TEAM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'fire_ice_fullroom_champions_regma_v1', 'Calibration room team built from shipped legal catalog sets and public sample-team archetypes.', '{"assumption_register":["Roster was assembled from already-shipped legal sets to widen calibration coverage.","This is a calibration shell, not a pinned public paste."],"champion_pack_id":"fire_ice_fullroom_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Derived sample shell repaired to Champions Reg M-A legality by replacing the banned Ursaluna-Bloodmoon Assault Vest slot with a legal held item while preserving the same fullroom structure.","legality_status":"legal_inferred","provenance":{"author":"calibration","roster_source":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/","spread_source":"archetype-derived from shipped catalog","status":"derived","url":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"trick_room"}'::jsonb),
  ('zardx_snow_setup', 'ZardX Snow Setup', 'SAMPLE TEAM', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'zardx_snow_setup_champions_regma_v1', 'Calibration snow offense built from shipped legal catalog sets and public sample-team archetypes.', '{"assumption_register":["Roster was assembled from already-shipped legal sets to widen calibration coverage.","This is a calibration shell, not a pinned public paste."],"champion_pack_id":"zardx_snow_setup_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Derived sample shell repaired to Champions Reg M-A legality by replacing the banned Milotic Life Orb slot with a legal held item while preserving the same Zard X snow setup shell.","legality_status":"legal_inferred","provenance":{"author":"calibration","roster_source":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/","spread_source":"archetype-derived from shipped catalog","status":"derived","url":"https://www.smogon.com/forums/threads/4v4-doubles-uu-regulation-m-a.3774137/"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"snow_mega"}'::jsonb),
  ('targeted_stat_source_proof', 'Targeted Stat Source Proof', 'QA STAT', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'targeted_stat_source_proof_champions_regma_v1', 'Legal Champions QA proof team for non-standard damage stat-source evidence: Foul Play uses the target Attack, Body Press uses the user''s Defense, and Psyshock-style special damage targets Defense.', '{"assumption_register":["This is a QA proof team, not a tournament paste.","Use Sableye to force Foul Play target-Attack traces, Orthworm or Kommo-o to force Body Press user-Defense traces, and Hatterene to force Psyshock target-Defense traces."],"champion_pack_id":"targeted_stat_source_proof_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Purpose-built legal Champions proof team. Species are active runtime-supported Reg M-A entries, moves are already represented in the generated Showdown-backed move tables, items are in the verified Champions pool, and SP spreads obey 32-per-stat/66-total caps.","legality_status":"legal","provenance":{"author":"qa","roster_source":"repo QA targeted proof coverage","spread_source":"legal Champions SP proof spreads","status":"proof-team","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"qa_proof"}'::jsonb),
  ('targeted_proof_legal', 'Targeted Proof Legal', 'QA PROOF', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'targeted_proof_legal_champions_regma_v1', 'Legal Champions QA proof team for targeted evidence: Shed Tail or Clangorous Soul HP cost, Wish delayed recovery, and Leech Seed residual drain.', '{"assumption_register":["This is a QA proof team, not a tournament paste.","Use Orthworm or Kommo-o for HP-cost proof, Kangaskhan for Wish delayed recovery proof, and Meganium for Leech Seed residual drain proof."],"champion_pack_id":"targeted_proof_legal_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Purpose-built legal Champions proof team. All species are allowed in Reg M-A, items are in the verified Champions pool, SP spreads obey 32-per-stat/66-total caps, and moves pass the generated Showdown-backed species/form legality gate.","legality_status":"legal","provenance":{"author":"qa","roster_source":"repo QA targeted proof coverage","spread_source":"legal Champions SP proof spreads","status":"proof-team","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"style":"balance"}'::jsonb),
  ('indeedee_hatterene_tr', 'Indeedee Hatterene Trick Room', 'REG M', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'indeedee_hatterene_tr_champions_regma_v1', 'Psychic Terrain + double Trick Room pressure built around Indeedee-F redirection, Hatterene burst turns, and slow-mode cleanup from Torkoal and Kingambit.', '{"assumption_register":["This is a competitive preloaded ladder/team-lab row, not a claimed event paste.","The goal is to cover Psychic Terrain redirection, Trick Room sequencing, and slow-mode win conditions in the visible approved runtime lane."],"champion_pack_id":"indeedee_hatterene_tr_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Built only from runtime-supported Champions Reg M-A species/forms with generated Showdown-backed move support and Champions-legal SP spreads. Added as a safe current-reg style lane without introducing unverified Reg M-B-only Mega rows.","legality_status":"legal","provenance":{"author":"codex","roster_source":"repo competitive expansion","spread_source":"legal Champions runtime-supported spreads","status":"approved-runtime","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"trick_room"}'::jsonb),
  ('rillaboom_archaludon_balance', 'Rillaboom Archaludon Balance', 'REG M', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'rillaboom_archaludon_balance_champions_regma_v1', 'Modern balance shell using Grassy Surge tempo, Pelipper rain support, Archaludon pressure, and Gholdengo/Kingambit endgames.', '{"assumption_register":["This is a competitive preloaded ladder/team-lab row, not a claimed event paste.","The goal is to add a current-reg balance shell that exercises terrain, Tailwind, rain pressure, and defensive pivoting."],"champion_pack_id":"rillaboom_archaludon_balance_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Built only from runtime-supported Champions Reg M-A species/forms with generated Showdown-backed move support and Champions-legal SP spreads. Added to cover Grassy Terrain pacing, rain-supported pressure, and recovery/tempo lines in the approved lane.","legality_status":"legal","provenance":{"author":"codex","roster_source":"repo competitive expansion","spread_source":"legal Champions runtime-supported spreads","status":"approved-runtime","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"balance"}'::jsonb),
  ('arboliva_seed_sower_balance', 'Arboliva Seed Sower Balance', 'REG M', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'arboliva_seed_sower_balance_champions_regma_v1', 'Reactive Grassy Terrain balance shell built around Arboliva sustain, Pelipper speed support, and mixed-pressure endgames from Archaludon, Gholdengo, and Garchomp.', '{"assumption_register":["This is a competitive preloaded ladder/team-lab row, not a claimed event paste.","The goal is to create visible approved coverage for terrain flips, sustain sequencing, and cleanup lines after terrain-trigger turns."],"champion_pack_id":"arboliva_seed_sower_balance_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Built only from runtime-supported Champions Reg M-A species/forms with generated Showdown-backed move support and Champions-legal SP spreads. Added to cover reactive Grassy Terrain, sustain loops, and mixed-speed balance in the approved lane.","legality_status":"legal","provenance":{"author":"codex","roster_source":"repo competitive expansion","spread_source":"legal Champions runtime-supported spreads","status":"approved-runtime","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"balance"}'::jsonb),
  ('pelipper_basculegion_rain', 'Pelipper Basculegion Rain', 'REG M', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'pelipper_basculegion_rain_champions_regma_v1', 'Rain offense with Pelipper speed control, Basculegion burst pressure, Rillaboom terrain pivoting, and Gholdengo endgame cleanup.', '{"assumption_register":["This is a competitive preloaded ladder/team-lab row, not a claimed event paste.","The goal is to add a fast weather shell that exercises rain offense, Tailwind timing, and terrain-weather pivot decisions."],"champion_pack_id":"pelipper_basculegion_rain_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Built only from runtime-supported Champions Reg M-A species/forms with generated Showdown-backed move support and Champions-legal SP spreads. Added to cover true rain offense in the approved runtime lane.","legality_status":"legal","provenance":{"author":"codex","roster_source":"repo competitive expansion","spread_source":"legal Champions runtime-supported spreads","status":"approved-runtime","url":""},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"weather"}'::jsonb),
  ('kevin_meta_sun', 'Kevin Meta Sun', 'KEVIN', 'opponent', 'champions_reg_m_doubles_bo3', 'builtin', 'kevin_meta_sun_champions_regma_v1', 'High-floor current-meta sun offense for real-play testing: Mega Charizard Y pressure, Venusaur sleep control, Garchomp spread pressure, Sneasler disruption, Incineroar pivoting, and Whimsicott speed control.', '{"assumption_register":["This is a real-play legal Champions team recommendation, not a claim of absolute solved best six.","The closest public meta source shell was Aaron Zheng''s Charizard Y sun team on Game8, but Whimsicott replaces the weaker current runtime Rotom-Wash lane to keep both real-play direction and in-app legality clean."],"champion_pack_id":"kevin_meta_sun_champions_regma_v1","format":"champions","formatid":"champions-vgc-2026-regma","gametype":"doubles","legality_notes":"Built to stay inside the verified Champions item pool and current runtime-supported move/species lane. The shell follows the current Charizard Y sun direction surfaced by Game8 and the current doubles tier list, but uses only moves the app can validate today.","legality_status":"legal","provenance":{"author":"codex","roster_source":"current meta adaptation from Game8 doubles best teams + doubles tier list","spread_source":"Game8 listed Champions spreads adapted only where current runtime-supported move legality required it","status":"approved-runtime","url":"https://game8.co/games/Pokemon-Champions/archives/593949"},"ruleset":["Species Clause","Item Clause","Bring 6 Pick 4","Level 50"],"source":"preloaded","style":"weather"}'::jsonb)
ON CONFLICT (team_id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  mode = EXCLUDED.mode,
  ruleset_id = EXCLUDED.ruleset_id,
  source = EXCLUDED.source,
  source_ref = EXCLUDED.source_ref,
  description = EXCLUDED.description,
  metadata = EXCLUDED.metadata;

-- Retire stale built-in rows that are no longer part of the reviewed repo catalog.
-- They stay available for historical FK references but cannot remain active selector/training rows.
UPDATE teams
SET metadata = COALESCE(metadata, '{}'::jsonb) || '{"retired":true,"retired_reason":"not_in_current_legal_repo_catalog"}'::jsonb
WHERE team_id NOT IN (
  'player',
  'mega_altaria',
  'mega_dragonite',
  'mega_houndoom',
  'rin_sand',
  'suica_sun',
  'cofagrigus_tr',
  'champions_arena_1st',
  'champions_arena_2nd',
  'champions_arena_3rd',
  'aurora_veil_froslass',
  'custom_1776995210260',
  'perish_trap_gengar',
  'rain_offense',
  'trick_room_golurk',
  'sun_offense_charizard',
  'z2r_feitosa_mega_floette',
  'benny_v_mega_froslass',
  'lukasjoel1_sand_gengar',
  'hiroto_imai_snow',
  'fedecampovgc_aerodactyl_ariados',
  'swirlingroses_meganium_vivillon',
  'prro_t_floette_aerodactyl',
  'fabulous_sunroom',
  'sand_bulky_offense',
  'fire_ice_fullroom',
  'zardx_snow_setup',
  'targeted_stat_source_proof',
  'targeted_proof_legal',
  'indeedee_hatterene_tr',
  'rillaboom_archaludon_balance',
  'arboliva_seed_sower_balance',
  'pelipper_basculegion_rain',
  'kevin_meta_sun'
)
  AND source = 'builtin'
  AND COALESCE(metadata->>'retired', 'false') <> 'true';

-- Replace normalized members for shared canonical repo teams only.
DELETE FROM team_members WHERE team_id IN (
  'player',
  'mega_altaria',
  'mega_dragonite',
  'mega_houndoom',
  'rin_sand',
  'suica_sun',
  'cofagrigus_tr',
  'champions_arena_1st',
  'champions_arena_2nd',
  'champions_arena_3rd',
  'aurora_veil_froslass',
  'custom_1776995210260',
  'perish_trap_gengar',
  'rain_offense',
  'trick_room_golurk',
  'sun_offense_charizard',
  'z2r_feitosa_mega_floette',
  'benny_v_mega_froslass',
  'lukasjoel1_sand_gengar',
  'hiroto_imai_snow',
  'fedecampovgc_aerodactyl_ariados',
  'swirlingroses_meganium_vivillon',
  'prro_t_floette_aerodactyl',
  'fabulous_sunroom',
  'sand_bulky_offense',
  'fire_ice_fullroom',
  'zardx_snow_setup',
  'targeted_stat_source_proof',
  'targeted_proof_legal',
  'indeedee_hatterene_tr',
  'rillaboom_archaludon_balance',
  'arboliva_seed_sower_balance',
  'pelipper_basculegion_rain',
  'kevin_meta_sun'
);

-- ============================================================
-- TEAM MEMBERS
-- ============================================================

-- player
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('player', 1, 'Incineroar', 'Sitrus Berry', 'Intimidate', 'Adamant', 50, '{"atk":8,"def":0,"hp":32,"spa":0,"spd":18,"spe":8}'::jsonb, '["Fake Out","Flare Blitz","U-turn","Knock Off"]'::jsonb, NULL, 'Support / Pivot'),
  ('player', 2, 'Arcanine', 'Charcoal', 'Intimidate', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Flare Blitz","Close Combat","Extreme Speed","Will-O-Wisp"]'::jsonb, NULL, 'TR Breaker / Speed Control'),
  ('player', 3, 'Garchomp', 'Soft Sand', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Dragon Claw","Rock Slide","Protect"]'::jsonb, NULL, 'Physical Sweeper'),
  ('player', 4, 'Whimsicott', 'Focus Sash', 'Prankster', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Tailwind","Sunny Day","Moonblast","Protect"]'::jsonb, NULL, 'Speed Control'),
  ('player', 5, 'Rotom-Wash', 'Leftovers', 'Levitate', 'Bold', 50, '{"atk":0,"def":8,"hp":32,"spa":26,"spd":0,"spe":0}'::jsonb, '["Thunderbolt","Hydro Pump","Will-O-Wisp","Protect"]'::jsonb, NULL, 'Spread Check'),
  ('player', 6, 'Dragapult', 'Choice Scarf', 'Clear Body', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Dragon Darts","U-turn","Phantom Force","Sucker Punch"]'::jsonb, NULL, 'Speed Control / Scarf Revenge');

-- mega_altaria
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('mega_altaria', 1, 'Typhlosion-Hisui', 'Choice Scarf', 'Frisk', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Eruption","Heat Wave","Focus Blast","Shadow Ball"]'::jsonb, NULL, 'Scarfer'),
  ('mega_altaria', 2, 'Altaria-Mega', 'Altarianite', 'Cloud Nine', 'Modest', 50, '{"atk":0,"def":0,"hp":32,"spa":10,"spd":17,"spe":7}'::jsonb, '["Protect","Roost","Flamethrower","Hyper Voice"]'::jsonb, NULL, 'Mega Sweeper'),
  ('mega_altaria', 3, 'Whimsicott', 'Focus Sash', 'Prankster', 'Serious', 50, '{"atk":0,"def":1,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Protect","Sunny Day","Tailwind","Moonblast"]'::jsonb, NULL, 'Speed Control'),
  ('mega_altaria', 4, 'Rotom-Wash', 'Leftovers', 'Levitate', 'Modest', 50, '{"atk":0,"def":10,"hp":32,"spa":23,"spd":0,"spe":1}'::jsonb, '["Protect","Will-O-Wisp","Thunderbolt","Hydro Pump"]'::jsonb, NULL, 'Spread Attacker'),
  ('mega_altaria', 5, 'Sableye', 'Black Glasses', 'Prankster', 'Calm', 50, '{"atk":0,"def":8,"hp":32,"spa":0,"spd":26,"spe":0}'::jsonb, '["Reflect","Light Screen","Recover","Foul Play"]'::jsonb, NULL, 'Screen Setter'),
  ('mega_altaria', 6, 'Sinistcha', 'Sitrus Berry', 'Hospitality', 'Bold', 50, '{"atk":0,"def":30,"hp":32,"spa":1,"spd":1,"spe":2}'::jsonb, '["Trick Room","Life Dew","Rage Powder","Matcha Gotcha"]'::jsonb, NULL, 'TR Setter');

-- mega_dragonite
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('mega_dragonite', 1, 'Dragonite-Mega', 'Dragoninite', 'Multiscale', 'Modest', 50, '{"atk":0,"def":0,"hp":26,"spa":32,"spd":0,"spe":8}'::jsonb, '["Protect","Ice Beam","Thunder","Hurricane"]'::jsonb, NULL, 'Mega Sweeper'),
  ('mega_dragonite', 2, 'Basculegion', 'Choice Scarf', 'Adaptability', 'Jolly', 50, '{"atk":32,"def":2,"hp":0,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Aqua Jet","Flip Turn","Last Respects"]'::jsonb, NULL, 'Scarfer'),
  ('mega_dragonite', 3, 'Liepard', 'Focus Sash', 'Prankster', 'Serious', 50, '{"atk":0,"def":1,"hp":32,"spa":0,"spd":1,"spe":32}'::jsonb, '["Fake Out","Rain Dance","Thunder Wave","Foul Play"]'::jsonb, NULL, 'Support'),
  ('mega_dragonite', 4, 'Archaludon', 'Quick Claw', 'Sturdy', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":1,"spe":32}'::jsonb, '["Protect","Flash Cannon","Dragon Pulse","Electro Shot"]'::jsonb, NULL, 'Rain Abuser'),
  ('mega_dragonite', 5, 'Pelipper', 'Leftovers', 'Drizzle', 'Modest', 50, '{"atk":0,"def":0,"hp":32,"spa":5,"spd":29,"spe":0}'::jsonb, '["Protect","Tailwind","U-turn","Weather Ball"]'::jsonb, NULL, 'Rain Setter'),
  ('mega_dragonite', 6, 'Orthworm', 'Sitrus Berry', 'Earth Eater', 'Careful', 50, '{"atk":1,"def":1,"hp":31,"spa":0,"spd":32,"spe":1}'::jsonb, '["Protect","Helping Hand","Shed Tail","Iron Head"]'::jsonb, NULL, 'Support');

-- mega_houndoom
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('mega_houndoom', 1, 'Houndoom-Mega', 'Houndoominite', 'Solar Power', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":1,"spe":32}'::jsonb, '["Protect","Flamethrower","Dark Pulse","Heat Wave"]'::jsonb, NULL, 'Mega Sweeper'),
  ('mega_houndoom', 2, 'Torkoal', 'Charcoal', 'Drought', 'Quiet', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":1,"spe":0}'::jsonb, '["Protect","Helping Hand","Heat Wave","Eruption"]'::jsonb, NULL, 'Sun Setter'),
  ('mega_houndoom', 3, 'Whimsicott', 'Focus Sash', 'Prankster', 'Modest', 50, '{"atk":0,"def":0,"hp":32,"spa":32,"spd":1,"spe":1}'::jsonb, '["Trick Room","Tailwind","Sunny Day","Moonblast"]'::jsonb, NULL, 'TR/Speed Control'),
  ('mega_houndoom', 4, 'Farigiraf', 'Mental Herb', 'Armor Tail', 'Relaxed', 50, '{"atk":0,"def":20,"hp":26,"spa":1,"spd":19,"spe":0}'::jsonb, '["Trick Room","Helping Hand","Psychic Noise","Hyper Voice"]'::jsonb, NULL, 'TR Setter'),
  ('mega_houndoom', 5, 'Sinistcha', 'Sitrus Berry', 'Hospitality', 'Bold', 50, '{"atk":0,"def":31,"hp":32,"spa":1,"spd":1,"spe":1}'::jsonb, '["Trick Room","Rage Powder","Life Dew","Matcha Gotcha"]'::jsonb, NULL, 'TR Setter'),
  ('mega_houndoom', 6, 'Drampa-Mega', 'Drampanite', 'Cloud Nine', 'Quiet', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Draco Meteor","Hyper Voice","Heat Wave","Thunderbolt"]'::jsonb, NULL, 'Mega Sweeper');

-- rin_sand
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('rin_sand', 1, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":24,"def":3,"hp":6,"spa":0,"spd":1,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Protect","Taunt"]'::jsonb, NULL, 'Unburden Attacker'),
  ('rin_sand', 2, 'Tyranitar', 'Chople Berry', 'Sand Stream', 'Adamant', 50, '{"atk":16,"def":12,"hp":32,"spa":0,"spd":2,"spe":4}'::jsonb, '["Rock Slide","Knock Off","Protect","Ice Punch"]'::jsonb, NULL, 'Sand Setter'),
  ('rin_sand', 3, 'Rotom-Wash', 'Sitrus Berry', 'Levitate', 'Modest', 50, '{"atk":0,"def":1,"hp":31,"spa":5,"spd":17,"spe":12}'::jsonb, '["Thunderbolt","Hydro Pump","Protect","Volt Switch"]'::jsonb, NULL, 'Pivot'),
  ('rin_sand', 4, 'Excadrill', 'Focus Sash', 'Sand Rush', 'Jolly', 50, '{"atk":32,"def":1,"hp":0,"spa":0,"spd":1,"spe":32}'::jsonb, '["High Horsepower","Iron Head","Protect","Earthquake"]'::jsonb, NULL, 'Sand Rush Sweeper'),
  ('rin_sand', 5, 'Dragapult', 'Colbur Berry', 'Clear Body', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Dragon Darts","Phantom Force","Protect","Will-O-Wisp"]'::jsonb, NULL, 'Fast Attacker'),
  ('rin_sand', 6, 'Meganium', 'Meganiumite', 'Overgrow', 'Modest', 50, '{"atk":0,"def":0,"hp":26,"spa":32,"spd":0,"spe":8}'::jsonb, '["Solar Beam","Energy Ball","Protect","Weather Ball"]'::jsonb, NULL, 'Mega Support');

-- suica_sun
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('suica_sun', 1, 'Charizard', 'Charizardite Y', 'Blaze', 'Modest', 50, '{"atk":0,"def":16,"hp":6,"spa":31,"spd":0,"spe":13}'::jsonb, '["Heat Wave","Air Slash","Weather Ball","Protect"]'::jsonb, NULL, 'Mega Sweeper'),
  ('suica_sun', 2, 'Sneasler', 'White Herb', 'Unburden', 'Adamant', 50, '{"atk":32,"def":2,"hp":0,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Rock Slide","Protect"]'::jsonb, NULL, 'Physical Sweeper'),
  ('suica_sun', 3, 'Basculegion', 'Choice Scarf', 'Adaptability', 'Jolly', 50, '{"atk":32,"def":2,"hp":0,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Last Respects","Aqua Jet","Flip Turn"]'::jsonb, NULL, 'Scarfer'),
  ('suica_sun', 4, 'Garchomp', 'Haban Berry', 'Rough Skin', 'Adamant', 50, '{"atk":20,"def":0,"hp":24,"spa":0,"spd":1,"spe":21}'::jsonb, '["Dragon Claw","Earthquake","Rock Slide","Protect"]'::jsonb, NULL, 'Physical Sweeper'),
  ('suica_sun', 5, 'Incineroar', 'Sitrus Berry', 'Intimidate', 'Adamant', 50, '{"atk":5,"def":7,"hp":32,"spa":0,"spd":16,"spe":6}'::jsonb, '["Throat Chop","Flare Blitz","U-turn","Fake Out"]'::jsonb, NULL, 'Support'),
  ('suica_sun', 6, 'Venusaur', 'Focus Sash', 'Chlorophyll', 'Modest', 50, '{"atk":0,"def":1,"hp":0,"spa":32,"spd":1,"spe":32}'::jsonb, '["Energy Ball","Sludge Bomb","Sleep Powder","Earth Power"]'::jsonb, NULL, 'Sun Abuser');

-- cofagrigus_tr
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('cofagrigus_tr', 1, 'Cofagrigus', 'Mental Herb', 'Mummy', 'Quiet', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Trick Room","Will-O-Wisp","Shadow Ball","Ally Switch"]'::jsonb, NULL, 'TR Setter'),
  ('cofagrigus_tr', 2, 'Sinistcha', 'Sitrus Berry', 'Hospitality', 'Quiet', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Trick Room","Matcha Gotcha","Rage Powder","Life Dew"]'::jsonb, NULL, 'TR Setter'),
  ('cofagrigus_tr', 3, 'Hatterene', 'Fairy Feather', 'Magic Bounce', 'Quiet', 50, '{"atk":0,"def":0,"hp":32,"spa":32,"spd":2,"spe":0}'::jsonb, '["Psychic","Dazzling Gleam","Shadow Ball","Protect"]'::jsonb, NULL, 'TR Sweeper'),
  ('cofagrigus_tr', 4, 'Farigiraf', 'Twisted Spoon', 'Armor Tail', 'Relaxed', 50, '{"atk":0,"def":18,"hp":32,"spa":2,"spd":14,"spe":0}'::jsonb, '["Trick Room","Helping Hand","Hyper Voice","Psychic Noise"]'::jsonb, NULL, 'TR Support'),
  ('cofagrigus_tr', 5, 'Dusclops', 'Colbur Berry', 'Pressure', 'Relaxed', 50, '{"atk":0,"def":18,"hp":32,"spa":0,"spd":16,"spe":0}'::jsonb, '["Trick Room","Will-O-Wisp","Shadow Sneak","Helping Hand"]'::jsonb, NULL, 'TR Support'),
  ('cofagrigus_tr', 6, 'Ursaluna-Bloodmoon', 'Leftovers', 'Mind''s Eye', 'Modest', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Blood Moon","Hyper Voice","Earth Power","Vacuum Wave"]'::jsonb, NULL, 'TR Sweeper / Tank');

-- champions_arena_1st
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('champions_arena_1st', 1, 'Charizard-Mega-Y', 'Charizardite Y', 'Drought', 'Modest', 50, '{"atk":0,"def":16,"hp":6,"spa":30,"spd":0,"spe":14}'::jsonb, '["Heat Wave","Weather Ball","Solar Beam","Protect"]'::jsonb, NULL, 'Sun Setter / Spread Attacker'),
  ('champions_arena_1st', 2, 'Milotic', 'Leftovers', 'Competitive', 'Bold', 50, '{"atk":0,"def":21,"hp":31,"spa":1,"spd":12,"spe":1}'::jsonb, '["Muddy Water","Coil","Haze","Recover"]'::jsonb, NULL, 'Utility / Secret Weapon'),
  ('champions_arena_1st', 3, 'Incineroar', 'Chople Berry', 'Intimidate', 'Serious', 50, '{"atk":0,"def":11,"hp":32,"spa":0,"spd":16,"spe":7}'::jsonb, '["Throat Chop","U-turn","Fake Out","Flare Blitz"]'::jsonb, NULL, 'Support / Pivot'),
  ('champions_arena_1st', 4, 'Sneasler', 'White Herb', 'Unburden', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Taunt","Close Combat","Dire Claw","Protect"]'::jsonb, NULL, 'Unburden Sweeper'),
  ('champions_arena_1st', 5, 'Garchomp', 'Sitrus Berry', 'Rough Skin', 'Adamant', 50, '{"atk":19,"def":0,"hp":24,"spa":0,"spd":1,"spe":22}'::jsonb, '["Dragon Claw","Rock Slide","Earthquake","Protect"]'::jsonb, NULL, 'Physical Sweeper'),
  ('champions_arena_1st', 6, 'Venusaur', 'Focus Sash', 'Chlorophyll', 'Modest', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Energy Ball","Sludge Bomb","Sleep Powder","Protect"]'::jsonb, NULL, 'Chlorophyll Sweeper');

-- champions_arena_2nd
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('champions_arena_2nd', 1, 'Charizard-Mega-X', 'Charizardite X', 'Tough Claws', 'Adamant', 50, '{"atk":21,"def":1,"hp":14,"spa":0,"spd":1,"spe":29}'::jsonb, '["Flare Blitz","Dragon Claw","Dragon Dance","Protect"]'::jsonb, NULL, 'Setup Sweeper'),
  ('champions_arena_2nd', 2, 'Milotic', 'Leftovers', 'Competitive', 'Calm', 50, '{"atk":0,"def":22,"hp":29,"spa":1,"spd":0,"spe":14}'::jsonb, '["Icy Wind","Scald","Protect","Recover"]'::jsonb, NULL, 'Speed Control / Pivot'),
  ('champions_arena_2nd', 3, 'Sinistcha', 'Coba Berry', 'Hospitality', 'Bold', 50, '{"atk":0,"def":5,"hp":31,"spa":1,"spd":29,"spe":0}'::jsonb, '["Matcha Gotcha","Rage Powder","Life Dew","Trick Room"]'::jsonb, NULL, 'TR Setter / Redirect'),
  ('champions_arena_2nd', 4, 'Tyranitar-Mega', 'Tyranitarite', 'Sand Stream', 'Adamant', 50, '{"atk":26,"def":1,"hp":17,"spa":0,"spd":1,"spe":21}'::jsonb, '["Rock Slide","Crunch","High Horsepower","Protect"]'::jsonb, NULL, 'Sand Setter / Physical Attacker'),
  ('champions_arena_2nd', 5, 'Incineroar', 'Sitrus Berry', 'Intimidate', 'Adamant', 50, '{"atk":5,"def":10,"hp":30,"spa":0,"spd":10,"spe":11}'::jsonb, '["Flare Blitz","Throat Chop","Fake Out","U-turn"]'::jsonb, NULL, 'Support / Pivot'),
  ('champions_arena_2nd', 6, 'Sneasler', 'White Herb', 'Unburden', 'Adamant', 50, '{"atk":32,"def":0,"hp":0,"spa":0,"spd":2,"spe":32}'::jsonb, '["Dire Claw","Taunt","Close Combat","Coaching"]'::jsonb, NULL, 'Unburden Sweeper');

-- champions_arena_3rd
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('champions_arena_3rd', 1, 'Charizard-Mega-Y', 'Charizardite Y', 'Drought', 'Timid', 50, '{"atk":0,"def":5,"hp":10,"spa":18,"spd":1,"spe":32}'::jsonb, '["Protect","Heat Wave","Overheat","Solar Beam"]'::jsonb, NULL, 'Sun Setter / Spread Attacker'),
  ('champions_arena_3rd', 2, 'Farigiraf', 'Sitrus Berry', 'Armor Tail', 'Modest', 50, '{"atk":0,"def":12,"hp":31,"spa":10,"spd":13,"spe":0}'::jsonb, '["Psychic","Imprison","Trick Room","Hyper Voice"]'::jsonb, NULL, 'TR Setter / Priority Blocker'),
  ('champions_arena_3rd', 3, 'Garchomp', 'Choice Scarf', 'Rough Skin', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Dragon Claw","Rock Slide","Stomping Tantrum"]'::jsonb, NULL, 'Speed Control / Sweeper'),
  ('champions_arena_3rd', 4, 'Whimsicott', 'Focus Sash', 'Prankster', 'Timid', 50, '{"atk":0,"def":10,"hp":32,"spa":2,"spd":0,"spe":22}'::jsonb, '["Protect","Moonblast","Tailwind","Encore"]'::jsonb, NULL, 'Prankster Support'),
  ('champions_arena_3rd', 5, 'Sneasler', 'White Herb', 'Unburden', 'Adamant', 50, '{"atk":20,"def":5,"hp":8,"spa":0,"spd":1,"spe":32}'::jsonb, '["Dire Claw","Fake Out","Close Combat","Protect"]'::jsonb, NULL, 'Unburden Sweeper'),
  ('champions_arena_3rd', 6, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":25,"def":2,"hp":6,"spa":0,"spd":1,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Low Kick","Protect"]'::jsonb, NULL, 'Late-Game Sweeper');

-- aurora_veil_froslass
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('aurora_veil_froslass', 1, 'Froslass-Mega', 'Froslassite', 'Snow Warning', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Aurora Veil","Blizzard","Shadow Ball","Protect"]'::jsonb, NULL, 'Veil Setter / Attacker'),
  ('aurora_veil_froslass', 2, 'Dragonite', 'Lum Berry', 'Multiscale', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Extreme Speed","Dragon Dance","Fire Punch","Protect"]'::jsonb, NULL, 'Multiscale Setup Sweeper'),
  ('aurora_veil_froslass', 3, 'Kingambit', 'Chople Berry', 'Supreme Overlord', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Iron Head","Low Kick","Protect"]'::jsonb, NULL, 'Supreme Overlord Sweeper'),
  ('aurora_veil_froslass', 4, 'Milotic', 'Leftovers', 'Competitive', 'Modest', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Scald","Ice Beam","Life Dew","Protect"]'::jsonb, NULL, 'Competitive Attacker'),
  ('aurora_veil_froslass', 5, 'Incineroar', 'Sitrus Berry', 'Intimidate', 'Careful', 50, '{"atk":2,"def":0,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Fake Out","U-turn","Flare Blitz","Knock Off"]'::jsonb, NULL, 'Support / Pivot'),
  ('aurora_veil_froslass', 6, 'Garchomp', 'Roseli Berry', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Rock Slide","Dragon Claw","Protect"]'::jsonb, NULL, 'Physical Pressure');

-- custom_1776995210260
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('custom_1776995210260', 1, 'Froslass', 'Froslassite', 'Snow Cloak', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Blizzard","Shadow Ball","Aurora Veil","Protect"]'::jsonb, NULL, ''),
  ('custom_1776995210260', 2, 'Glaceon', 'Shell Bell', 'Ice Body', 'Modest', 50, '{"atk":0,"def":32,"hp":0,"spa":32,"spd":2,"spe":0}'::jsonb, '["Blizzard","Freeze-Dry","Protect","Calm Mind"]'::jsonb, NULL, ''),
  ('custom_1776995210260', 3, 'Ninetales-Alola', 'Focus Sash', 'Snow Warning', 'Modest', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Aurora Veil","Blizzard","Moonblast","Encore"]'::jsonb, NULL, ''),
  ('custom_1776995210260', 4, 'Milotic', 'Leftovers', 'Competitive', 'Calm', 50, '{"atk":0,"def":0,"hp":0,"spa":32,"spd":32,"spe":2}'::jsonb, '["Blizzard","Scald","Weather Ball","Life Dew"]'::jsonb, NULL, ''),
  ('custom_1776995210260', 5, 'Sneasler', 'Sitrus Berry', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Fake Out","Dire Claw","Close Combat","Rock Tomb"]'::jsonb, NULL, ''),
  ('custom_1776995210260', 6, 'Farigiraf', 'Choice Scarf', 'Cud Chew', 'Modest', 50, '{"atk":0,"def":0,"hp":32,"spa":32,"spd":2,"spe":0}'::jsonb, '["Hyper Voice","Psychic","Trick Room","Protect"]'::jsonb, NULL, '');

-- perish_trap_gengar
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('perish_trap_gengar', 1, 'Gengar-Mega', 'Gengarite', 'Shadow Tag', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Shadow Ball","Sludge Bomb","Perish Song","Protect"]'::jsonb, NULL, 'Mega Trapper'),
  ('perish_trap_gengar', 2, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Low Kick","Protect"]'::jsonb, NULL, 'Late-Game Sweeper'),
  ('perish_trap_gengar', 3, 'Sinistcha', 'Sitrus Berry', 'Hospitality', 'Relaxed', 50, '{"atk":0,"def":32,"hp":32,"spa":1,"spd":0,"spe":0}'::jsonb, '["Matcha Gotcha","Trick Room","Rage Powder","Protect"]'::jsonb, NULL, 'Redirection Support'),
  ('perish_trap_gengar', 4, 'Incineroar', 'Chople Berry', 'Intimidate', 'Careful', 50, '{"atk":1,"def":0,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Flare Blitz","Protect","Parting Shot","Fake Out"]'::jsonb, NULL, 'Pivot / Fake Out'),
  ('perish_trap_gengar', 5, 'Kommo-o', 'Leftovers', 'Overcoat', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Clanging Scales","Aura Sphere","Clangorous Soul","Protect"]'::jsonb, NULL, 'Late Cleaner'),
  ('perish_trap_gengar', 6, 'Aerodactyl', 'Focus Sash', 'Unnerve', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Tailwind","Dual Wingbeat","Rock Slide","Protect"]'::jsonb, NULL, 'Speed Control');

-- rain_offense
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('rain_offense', 1, 'Meganium-Mega', 'Meganiumite', 'Mega Sol', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Solar Beam","Weather Ball","Dazzling Gleam","Protect"]'::jsonb, NULL, 'Mega Attacker'),
  ('rain_offense', 2, 'Sableye', 'Lum Berry', 'Prankster', 'Calm', 50, '{"atk":0,"def":1,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Foul Play","Rain Dance","Light Screen","Encore"]'::jsonb, NULL, 'Prankster Support'),
  ('rain_offense', 3, 'Archaludon', 'Sitrus Berry', 'Stamina', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Electro Shot","Draco Meteor","Flash Cannon","Protect"]'::jsonb, NULL, 'Rain SpA'),
  ('rain_offense', 4, 'Basculegion', 'Choice Scarf', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Flip Turn","Aqua Jet","Last Respects"]'::jsonb, NULL, 'Scarf Sweeper'),
  ('rain_offense', 5, 'Pelipper', 'Focus Sash', 'Drizzle', 'Modest', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Weather Ball","Hurricane","Tailwind","Protect"]'::jsonb, NULL, 'Weather Setter'),
  ('rain_offense', 6, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Protect"]'::jsonb, NULL, 'Unburden Sweeper');

-- trick_room_golurk
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('trick_room_golurk', 1, 'Incineroar', 'Shuca Berry', 'Intimidate', 'Careful', 50, '{"atk":1,"def":0,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Flare Blitz","Throat Chop","Parting Shot","Fake Out"]'::jsonb, NULL, 'Pivot'),
  ('trick_room_golurk', 2, 'Farigiraf', 'Sitrus Berry', 'Armor Tail', 'Relaxed', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Hyper Voice","Psychic","Helping Hand","Trick Room"]'::jsonb, NULL, 'TR Setter'),
  ('trick_room_golurk', 3, 'Golurk-Mega', 'Golurkite', 'Iron Fist', 'Brave', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Protect","Headlong Rush","Poltergeist","Ice Punch"]'::jsonb, NULL, 'Mega TR Sweeper'),
  ('trick_room_golurk', 4, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Coaching"]'::jsonb, NULL, 'Unburden'),
  ('trick_room_golurk', 5, 'Torkoal', 'Charcoal', 'Drought', 'Quiet', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Protect","Heat Wave","Eruption","Weather Ball"]'::jsonb, NULL, 'TR Attacker'),
  ('trick_room_golurk', 6, 'Venusaur', 'Focus Sash', 'Chlorophyll', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Protect","Leaf Storm","Sludge Bomb","Sleep Powder"]'::jsonb, NULL, 'Sun Abuser / Sash');

-- sun_offense_charizard
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('sun_offense_charizard', 1, 'Incineroar', 'White Herb', 'Intimidate', 'Adamant', 50, '{"atk":1,"def":0,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Flare Blitz","Darkest Lariat","Close Combat","Fake Out"]'::jsonb, NULL, 'Pivot'),
  ('sun_offense_charizard', 2, 'Hatterene', 'Fairy Feather', 'Magic Bounce', 'Relaxed', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Psychic","Trick Room","Dazzling Gleam","Protect"]'::jsonb, NULL, 'TR Setter'),
  ('sun_offense_charizard', 3, 'Farigiraf', 'Sitrus Berry', 'Armor Tail', 'Relaxed', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Hyper Voice","Trick Room","Psychic","Protect"]'::jsonb, NULL, 'TR Setter 2'),
  ('sun_offense_charizard', 4, 'Torkoal', 'Charcoal', 'Drought', 'Modest', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Eruption","Weather Ball","Earth Power","Protect"]'::jsonb, NULL, 'Sun Setter'),
  ('sun_offense_charizard', 5, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Iron Head","Swords Dance"]'::jsonb, NULL, 'Sweeper'),
  ('sun_offense_charizard', 6, 'Charizard-Mega-Y', 'Charizardite Y', 'Solar Power', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Heat Wave","Overheat","Solar Beam","Protect"]'::jsonb, NULL, 'Mega Attacker');

-- z2r_feitosa_mega_floette
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('z2r_feitosa_mega_floette', 1, 'Talonflame', 'Sharp Beak', 'Gale Wings', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Protect","Dual Wingbeat","Flare Blitz","Tailwind"]'::jsonb, NULL, 'Priority Tailwind'),
  ('z2r_feitosa_mega_floette', 2, 'Garchomp', 'Roseli Berry', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Protect","Rock Slide","Earthquake","Dragon Claw"]'::jsonb, NULL, 'Physical Attacker'),
  ('z2r_feitosa_mega_floette', 3, 'Basculegion', 'Sitrus Berry', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Protect","Liquidation","Last Respects","Aqua Jet"]'::jsonb, NULL, 'Revenge Killer'),
  ('z2r_feitosa_mega_floette', 4, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Protect","Sucker Punch","Iron Head","Kowtow Cleave"]'::jsonb, NULL, 'Late-Game Cleaner'),
  ('z2r_feitosa_mega_floette', 5, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Protect","Close Combat","Gunk Shot","Fake Out"]'::jsonb, NULL, 'Fast Attacker'),
  ('z2r_feitosa_mega_floette', 6, 'Floette (Eternal Flower)-Mega', 'Floettite', 'Fairy Aura', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Protect","Light of Ruin","Dazzling Gleam","Moonblast"]'::jsonb, NULL, 'Mega Special Wall-Breaker');

-- benny_v_mega_froslass
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('benny_v_mega_froslass', 1, 'Basculegion', 'Choice Scarf', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Last Respects","Icy Wind","Flip Turn"]'::jsonb, NULL, 'Scarf Sweeper'),
  ('benny_v_mega_froslass', 2, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Swords Dance","Protect"]'::jsonb, NULL, 'Late-Game Cleaner'),
  ('benny_v_mega_froslass', 3, 'Rotom-Heat', 'Leftovers', 'Levitate', 'Bold', 50, '{"atk":0,"def":32,"hp":32,"spa":0,"spd":1,"spe":0}'::jsonb, '["Thunderbolt","Overheat","Will-O-Wisp","Protect"]'::jsonb, NULL, 'Burn Support'),
  ('benny_v_mega_froslass', 4, 'Froslass-Mega', 'Froslassite', 'Snow Cloak', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Blizzard","Shadow Ball","Taunt","Protect"]'::jsonb, NULL, 'Mega Snow Attacker'),
  ('benny_v_mega_froslass', 5, 'Sneasler', 'Focus Sash', 'Poison Touch', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Protect"]'::jsonb, NULL, 'Fake Out + Sash'),
  ('benny_v_mega_froslass', 6, 'Clefable', 'Sitrus Berry', 'Unaware', 'Calm', 50, '{"atk":0,"def":1,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Moonblast","Follow Me","Helping Hand","Protect"]'::jsonb, NULL, 'Redirection');

-- lukasjoel1_sand_gengar
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('lukasjoel1_sand_gengar', 1, 'Garchomp', 'Bright Powder', 'Sand Veil', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Dragon Claw","Rock Slide","Protect"]'::jsonb, NULL, 'Sand Attacker'),
  ('lukasjoel1_sand_gengar', 2, 'Tyranitar', 'Shuca Berry', 'Sand Stream', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Rock Slide","Low Kick","Ice Punch","Protect"]'::jsonb, NULL, 'Sand Setter'),
  ('lukasjoel1_sand_gengar', 3, 'Gengar-Mega', 'Gengarite', 'Shadow Tag', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Shadow Ball","Sludge Wave","Focus Blast","Protect"]'::jsonb, NULL, 'Mega Trapper'),
  ('lukasjoel1_sand_gengar', 4, 'Whimsicott', 'Mental Herb', 'Prankster', 'Timid', 50, '{"atk":0,"def":1,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Moonblast","Protect","Tailwind","Fake Tears"]'::jsonb, NULL, 'Prankster Support'),
  ('lukasjoel1_sand_gengar', 5, 'Rotom-Wash', 'Leftovers', 'Levitate', 'Bold', 50, '{"atk":0,"def":32,"hp":32,"spa":0,"spd":1,"spe":0}'::jsonb, '["Hydro Pump","Volt Switch","Will-O-Wisp","Protect"]'::jsonb, NULL, 'Burn Pivot'),
  ('lukasjoel1_sand_gengar', 6, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Protect"]'::jsonb, NULL, 'Unburden Sweeper');

-- hiroto_imai_snow
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('hiroto_imai_snow', 1, 'Lopunny-Mega', 'Lopunnite', 'Limber', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Fake Out","Encore","Protect"]'::jsonb, NULL, 'Mega Fake Out'),
  ('hiroto_imai_snow', 2, 'Aegislash', 'Spell Tag', 'Stance Change', 'Brave', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Poltergeist","Close Combat","Shadow Sneak","King''s Shield"]'::jsonb, NULL, 'Stance Attacker'),
  ('hiroto_imai_snow', 3, 'Vanilluxe', 'Choice Scarf', 'Snow Warning', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Blizzard","Icy Wind","Freeze-Dry","Ice Shard"]'::jsonb, NULL, 'Snow Setter / Scarf'),
  ('hiroto_imai_snow', 4, 'Garchomp', 'White Herb', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Dragon Claw","Earthquake","Rock Slide","Protect"]'::jsonb, NULL, 'Physical Attacker'),
  ('hiroto_imai_snow', 5, 'Kingambit', 'Chople Berry', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Low Kick","Protect"]'::jsonb, NULL, 'Late-Game Cleaner'),
  ('hiroto_imai_snow', 6, 'Basculegion', 'Sitrus Berry', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Last Respects","Aqua Jet","Protect"]'::jsonb, NULL, 'Revenge Killer');

-- fedecampovgc_aerodactyl_ariados
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('fedecampovgc_aerodactyl_ariados', 1, 'Ariados', 'Focus Sash', 'Insomnia', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Lunge","Poison Jab","Sucker Punch","Protect"]'::jsonb, NULL, 'Utility Pressure'),
  ('fedecampovgc_aerodactyl_ariados', 2, 'Aerodactyl-Mega', 'Aerodactylite', 'Tough Claws', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Tailwind","Dual Wingbeat","Rock Slide","Protect"]'::jsonb, NULL, 'Mega Speed Control'),
  ('fedecampovgc_aerodactyl_ariados', 3, 'Charizard-Mega-Y', 'Charizardite Y', 'Drought', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Heat Wave","Solar Beam","Overheat","Protect"]'::jsonb, NULL, 'Sun Breaker'),
  ('fedecampovgc_aerodactyl_ariados', 4, 'Basculegion', 'Choice Scarf', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Last Respects","Aqua Jet","Flip Turn"]'::jsonb, NULL, 'Scarf Cleaner'),
  ('fedecampovgc_aerodactyl_ariados', 5, 'Sylveon', 'Leftovers', 'Pixilate', 'Modest', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Hyper Voice","Moonblast","Helping Hand","Protect"]'::jsonb, NULL, 'Fairy Support'),
  ('fedecampovgc_aerodactyl_ariados', 6, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Protect"]'::jsonb, NULL, 'Unburden Sweeper');

-- swirlingroses_meganium_vivillon
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('swirlingroses_meganium_vivillon', 1, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Protect"]'::jsonb, NULL, 'Unburden Sweeper'),
  ('swirlingroses_meganium_vivillon', 2, 'Basculegion', 'Mystic Water', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Last Respects","Aqua Jet","Protect"]'::jsonb, NULL, 'Physical Cleaner'),
  ('swirlingroses_meganium_vivillon', 3, 'Incineroar', 'Sitrus Berry', 'Intimidate', 'Careful', 50, '{"atk":1,"def":0,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Fake Out","Parting Shot","Flare Blitz","Knock Off"]'::jsonb, NULL, 'Pivot'),
  ('swirlingroses_meganium_vivillon', 4, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Low Kick","Protect"]'::jsonb, NULL, 'Late-Game Cleaner'),
  ('swirlingroses_meganium_vivillon', 5, 'Meganium', 'Leftovers', 'Overgrow', 'Calm', 50, '{"atk":0,"def":1,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Giga Drain","Dazzling Gleam","Leech Seed","Protect"]'::jsonb, NULL, 'Bulky Support'),
  ('swirlingroses_meganium_vivillon', 6, 'Vivillon-Continental', 'Focus Sash', 'Compound Eyes', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Sleep Powder","Hurricane","Tailwind","Protect"]'::jsonb, NULL, 'Fast Utility');

-- prro_t_floette_aerodactyl
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('prro_t_floette_aerodactyl', 1, 'Floette (Eternal Flower)', 'Fairy Feather', 'Flower Veil', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Light of Ruin","Dazzling Gleam","Moonblast","Protect"]'::jsonb, NULL, 'Fairy Breaker'),
  ('prro_t_floette_aerodactyl', 2, 'Aerodactyl', 'Focus Sash', 'Unnerve', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Tailwind","Dual Wingbeat","Rock Slide","Protect"]'::jsonb, NULL, 'Speed Control'),
  ('prro_t_floette_aerodactyl', 3, 'Incineroar', 'Chople Berry', 'Intimidate', 'Careful', 50, '{"atk":1,"def":0,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Fake Out","Parting Shot","Flare Blitz","Darkest Lariat"]'::jsonb, NULL, 'Pivot'),
  ('prro_t_floette_aerodactyl', 4, 'Garchomp', 'Soft Sand', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Dragon Claw","Rock Slide","Protect"]'::jsonb, NULL, 'Physical Pressure'),
  ('prro_t_floette_aerodactyl', 5, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Close Combat","Dire Claw","Fake Out","Protect"]'::jsonb, NULL, 'Unburden Sweeper'),
  ('prro_t_floette_aerodactyl', 6, 'Basculegion', 'Choice Scarf', 'Adaptability', 'Adamant', 50, '{"atk":32,"def":0,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Last Respects","Aqua Jet","Flip Turn"]'::jsonb, NULL, 'Scarf Cleaner');

-- fabulous_sunroom
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('fabulous_sunroom', 1, 'Charizard-Mega-Y', 'Charizardite Y', 'Drought', 'Modest', 50, '{"atk":0,"def":16,"hp":6,"spa":30,"spd":0,"spe":14}'::jsonb, '["Heat Wave","Weather Ball","Solar Beam","Protect"]'::jsonb, NULL, 'Sun Setter / Spread Attacker'),
  ('fabulous_sunroom', 2, 'Torkoal', 'Charcoal', 'Drought', 'Quiet', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":1,"spe":0}'::jsonb, '["Protect","Helping Hand","Heat Wave","Eruption"]'::jsonb, NULL, 'Sun Setter'),
  ('fabulous_sunroom', 3, 'Venusaur', 'Focus Sash', 'Chlorophyll', 'Modest', 50, '{"atk":0,"def":1,"hp":0,"spa":32,"spd":1,"spe":32}'::jsonb, '["Energy Ball","Sludge Bomb","Sleep Powder","Earth Power"]'::jsonb, NULL, 'Sun Abuser'),
  ('fabulous_sunroom', 4, 'Whimsicott', 'Sitrus Berry', 'Prankster', 'Timid', 50, '{"atk":0,"def":0,"hp":4,"spa":32,"spd":0,"spe":30}'::jsonb, '["Tailwind","Sunny Day","Moonblast","Protect"]'::jsonb, NULL, 'Speed Control'),
  ('fabulous_sunroom', 5, 'Arcanine', 'Roseli Berry', 'Intimidate', 'Adamant', 50, '{"atk":32,"def":0,"hp":4,"spa":0,"spd":0,"spe":30}'::jsonb, '["Power Gem","Head Smash","Extreme Speed","Will-O-Wisp"]'::jsonb, NULL, 'TR Breaker / Speed Control'),
  ('fabulous_sunroom', 6, 'Floette (Eternal Flower)-Mega', 'Floettite', 'Fairy Aura', 'Timid', 50, '{"atk":0,"def":0,"hp":4,"spa":32,"spd":0,"spe":30}'::jsonb, '["Protect","Light of Ruin","Dazzling Gleam","Moonblast"]'::jsonb, NULL, 'Mega Special Wall-Breaker');

-- sand_bulky_offense
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('sand_bulky_offense', 1, 'Tyranitar', 'Chople Berry', 'Sand Stream', 'Adamant', 50, '{"atk":16,"def":12,"hp":32,"spa":0,"spd":2,"spe":4}'::jsonb, '["Rock Slide","Knock Off","Protect","Ice Punch"]'::jsonb, NULL, 'Sand Setter'),
  ('sand_bulky_offense', 2, 'Excadrill', 'Focus Sash', 'Sand Rush', 'Jolly', 50, '{"atk":32,"def":1,"hp":0,"spa":0,"spd":1,"spe":32}'::jsonb, '["High Horsepower","Iron Head","Protect","Earthquake"]'::jsonb, NULL, 'Sand Rush Sweeper'),
  ('sand_bulky_offense', 3, 'Rotom-Wash', 'Leftovers', 'Levitate', 'Bold', 50, '{"atk":0,"def":0,"hp":31,"spa":32,"spd":0,"spe":3}'::jsonb, '["Thunderbolt","Hydro Pump","Will-O-Wisp","Protect"]'::jsonb, NULL, 'Spread Check'),
  ('sand_bulky_offense', 4, 'Milotic', 'Mystic Water', 'Competitive', 'Bold', 50, '{"atk":0,"def":21,"hp":31,"spa":1,"spd":12,"spe":1}'::jsonb, '["Muddy Water","Coil","Hypnosis","Recover"]'::jsonb, NULL, 'Utility / Secret Weapon'),
  ('sand_bulky_offense', 5, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":4,"spa":0,"spd":0,"spe":30}'::jsonb, '["Kowtow Cleave","Sucker Punch","Low Kick","Protect"]'::jsonb, NULL, 'Late-Game Sweeper'),
  ('sand_bulky_offense', 6, 'Gholdengo', 'Spell Tag', 'Good as Gold', 'Modest', 50, '{"atk":0,"def":0,"hp":4,"spa":32,"spd":0,"spe":30}'::jsonb, '["Make It Rain","Shadow Ball","Power Gem","Trick"]'::jsonb, NULL, 'Status-Immune Attacker');

-- fire_ice_fullroom
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('fire_ice_fullroom', 1, 'Farigiraf', 'Mental Herb', 'Armor Tail', 'Relaxed', 50, '{"atk":0,"def":20,"hp":26,"spa":1,"spd":19,"spe":0}'::jsonb, '["Trick Room","Helping Hand","Psychic Noise","Hyper Voice"]'::jsonb, NULL, 'TR Setter'),
  ('fire_ice_fullroom', 2, 'Cofagrigus', 'Colbur Berry', 'Mummy', 'Quiet', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Trick Room","Will-O-Wisp","Shadow Ball","Ally Switch"]'::jsonb, NULL, 'TR Setter'),
  ('fire_ice_fullroom', 3, 'Typhlosion-Hisui', 'Choice Scarf', 'Frisk', 'Timid', 50, '{"atk":0,"def":32,"hp":2,"spa":32,"spd":0,"spe":0}'::jsonb, '["Eruption","Heat Wave","Focus Blast","Shadow Ball"]'::jsonb, NULL, 'Scarfer'),
  ('fire_ice_fullroom', 4, 'Vanilluxe', 'Never-Melt Ice', 'Snow Warning', 'Modest', 50, '{"atk":0,"def":0,"hp":4,"spa":32,"spd":0,"spe":30}'::jsonb, '["Blizzard","Icy Wind","Freeze-Dry","Ice Shard"]'::jsonb, NULL, 'Snow Setter / Scarf'),
  ('fire_ice_fullroom', 5, 'Torkoal', 'Charcoal', 'Drought', 'Quiet', 50, '{"atk":0,"def":1,"hp":32,"spa":32,"spd":1,"spe":0}'::jsonb, '["Protect","Helping Hand","Heat Wave","Eruption"]'::jsonb, NULL, 'Sun Setter'),
  ('fire_ice_fullroom', 6, 'Ursaluna-Bloodmoon', 'Leftovers', 'Mind''s Eye', 'Modest', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Blood Moon","Hyper Voice","Earth Power","Vacuum Wave"]'::jsonb, NULL, 'TR Sweeper / Tank');

-- zardx_snow_setup
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('zardx_snow_setup', 1, 'Charizard-Mega-X', 'Charizardite X', 'Tough Claws', 'Adamant', 50, '{"atk":21,"def":1,"hp":14,"spa":0,"spd":1,"spe":29}'::jsonb, '["Flare Blitz","Dragon Claw","Dragon Dance","Protect"]'::jsonb, NULL, 'Setup Sweeper'),
  ('zardx_snow_setup', 2, 'Vanilluxe', 'Choice Scarf', 'Snow Warning', 'Modest', 50, '{"atk":0,"def":0,"hp":4,"spa":32,"spd":0,"spe":30}'::jsonb, '["Blizzard","Icy Wind","Freeze-Dry","Ice Shard"]'::jsonb, NULL, 'Snow Setter / Scarf'),
  ('zardx_snow_setup', 3, 'Froslass-Mega', 'Froslassite', 'Snow Warning', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Aurora Veil","Blizzard","Shadow Ball","Protect"]'::jsonb, NULL, 'Veil Setter / Attacker'),
  ('zardx_snow_setup', 4, 'Dragonite', 'Lum Berry', 'Multiscale', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Extreme Speed","Dragon Dance","Fire Punch","Protect"]'::jsonb, NULL, 'Multiscale Setup Sweeper'),
  ('zardx_snow_setup', 5, 'Kingambit', 'Chople Berry', 'Supreme Overlord', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Kowtow Cleave","Sucker Punch","Low Kick","Protect"]'::jsonb, NULL, 'Supreme Overlord Sweeper'),
  ('zardx_snow_setup', 6, 'Milotic', 'Leftovers', 'Competitive', 'Modest', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":32,"spe":0}'::jsonb, '["Blizzard","Scald","Weather Ball","Life Dew"]'::jsonb, NULL, 'Utility / Secret Weapon');

-- targeted_stat_source_proof
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('targeted_stat_source_proof', 1, 'Sableye', 'Black Glasses', 'Prankster', 'Impish', 50, '{"atk":0,"def":32,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Foul Play","Recover","Reflect","Protect"]'::jsonb, NULL, 'Foul Play Stat-Source Proof'),
  ('targeted_stat_source_proof', 2, 'Orthworm', 'Sitrus Berry', 'Earth Eater', 'Impish', 50, '{"atk":0,"def":32,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Body Press","Shed Tail","Protect","Helping Hand"]'::jsonb, NULL, 'Body Press Stat-Source Proof'),
  ('targeted_stat_source_proof', 3, 'Hatterene', 'Leftovers', 'Magic Bounce', 'Bold', 50, '{"atk":0,"def":32,"hp":32,"spa":2,"spd":0,"spe":0}'::jsonb, '["Psyshock","Trick Room","Recover","Protect"]'::jsonb, NULL, 'Psyshock Defense-Target Proof'),
  ('targeted_stat_source_proof', 4, 'Kommo-o', 'Dragon Fang', 'Overcoat', 'Impish', 50, '{"atk":0,"def":32,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Body Press","Clangorous Soul","Protect","Clanging Scales"]'::jsonb, NULL, 'Alternate Body Press Proof'),
  ('targeted_stat_source_proof', 5, 'Garchomp', 'Soft Sand', 'Rough Skin', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Dragon Claw","Rock Slide","Protect"]'::jsonb, NULL, 'High-Attack Foul Play Target'),
  ('targeted_stat_source_proof', 6, 'Pelipper', 'Focus Sash', 'Drizzle', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Tailwind","Weather Ball","U-turn","Protect"]'::jsonb, NULL, 'Weather / Speed Support');

-- targeted_proof_legal
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('targeted_proof_legal', 1, 'Orthworm', 'Sitrus Berry', 'Earth Eater', 'Careful', 50, '{"atk":1,"def":1,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Shed Tail","Protect","Helping Hand","Iron Head"]'::jsonb, NULL, 'HP-Cost Proof'),
  ('targeted_proof_legal', 2, 'Kangaskhan', 'Leftovers', 'Scrappy', 'Careful', 50, '{"atk":0,"def":32,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Wish","Protect","Fake Out","Body Slam"]'::jsonb, NULL, 'Delayed Recovery Proof'),
  ('targeted_proof_legal', 3, 'Meganium', 'Miracle Seed', 'Overgrow', 'Calm', 50, '{"atk":0,"def":1,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Leech Seed","Protect","Giga Drain","Synthesis"]'::jsonb, NULL, 'Residual Drain Proof'),
  ('targeted_proof_legal', 4, 'Garchomp', 'Soft Sand', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Tackle","Protect","Dragon Claw","Earthquake"]'::jsonb, NULL, 'Legal Target / Damage Probe'),
  ('targeted_proof_legal', 5, 'Kommo-o', 'Dragon Fang', 'Overcoat', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":0,"spe":32}'::jsonb, '["Clangorous Soul","Protect","Aura Sphere","Clanging Scales"]'::jsonb, NULL, 'Alternate HP-Cost Proof'),
  ('targeted_proof_legal', 6, 'Pelipper', 'Mystic Water', 'Drizzle', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Protect","Tailwind","Weather Ball","U-turn"]'::jsonb, NULL, 'Weather / Speed Support');

-- indeedee_hatterene_tr
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('indeedee_hatterene_tr', 1, 'Indeedee-F', 'Focus Sash', 'Psychic Surge', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Follow Me","Helping Hand","Expanding Force","Protect"]'::jsonb, NULL, 'Terrain / Redirection'),
  ('indeedee_hatterene_tr', 2, 'Hatterene', 'Leftovers', 'Magic Bounce', 'Quiet', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Trick Room","Expanding Force","Dazzling Gleam","Protect"]'::jsonb, NULL, 'Primary Trick Room Breaker'),
  ('indeedee_hatterene_tr', 3, 'Farigiraf', 'Sitrus Berry', 'Armor Tail', 'Sassy', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Trick Room","Helping Hand","Hyper Voice","Protect"]'::jsonb, NULL, 'Secondary Trick Room / Anti-Priority'),
  ('indeedee_hatterene_tr', 4, 'Torkoal', 'Charcoal', 'Drought', 'Quiet', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Eruption","Heat Wave","Yawn","Protect"]'::jsonb, NULL, 'Slow-Mode Damage'),
  ('indeedee_hatterene_tr', 5, 'Amoonguss', 'Lum Berry', 'Regenerator', 'Sassy', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Spore","Rage Powder","Pollen Puff","Protect"]'::jsonb, NULL, 'Redirection / Recovery Pivot'),
  ('indeedee_hatterene_tr', 6, 'Kingambit', 'Black Glasses', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Kowtow Cleave","Iron Head","Swords Dance","Protect"]'::jsonb, NULL, 'Backline Punish');

-- rillaboom_archaludon_balance
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('rillaboom_archaludon_balance', 1, 'Rillaboom', 'Miracle Seed', 'Grassy Surge', 'Adamant', 50, '{"atk":32,"def":0,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Grassy Glide","Wood Hammer","Knock Off","U-turn"]'::jsonb, NULL, 'Terrain Pivot'),
  ('rillaboom_archaludon_balance', 2, 'Pelipper', 'Focus Sash', 'Drizzle', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Tailwind","Hurricane","Weather Ball","Protect"]'::jsonb, NULL, 'Rain / Speed Control'),
  ('rillaboom_archaludon_balance', 3, 'Archaludon', 'Metal Coat', 'Stamina', 'Modest', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Electro Shot","Flash Cannon","Body Press","Protect"]'::jsonb, NULL, 'Rain Abuse Breaker'),
  ('rillaboom_archaludon_balance', 4, 'Gholdengo', 'Spell Tag', 'Good as Gold', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Make It Rain","Shadow Ball","Nasty Plot","Protect"]'::jsonb, NULL, 'Special Cleaner'),
  ('rillaboom_archaludon_balance', 5, 'Amoonguss', 'Sitrus Berry', 'Regenerator', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Spore","Rage Powder","Pollen Puff","Protect"]'::jsonb, NULL, 'Disruption / Sustain'),
  ('rillaboom_archaludon_balance', 6, 'Kingambit', 'Lum Berry', 'Defiant', 'Adamant', 50, '{"atk":32,"def":0,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Kowtow Cleave","Iron Head","Swords Dance","Protect"]'::jsonb, NULL, 'Physical Punish');

-- arboliva_seed_sower_balance
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('arboliva_seed_sower_balance', 1, 'Arboliva', 'Leftovers', 'Seed Sower', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Giga Drain","Pollen Puff","Terrain Pulse","Protect"]'::jsonb, NULL, 'Terrain Sustain Core'),
  ('arboliva_seed_sower_balance', 2, 'Pelipper', 'Focus Sash', 'Drizzle', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Tailwind","Hurricane","Weather Ball","Protect"]'::jsonb, NULL, 'Rain / Speed Control'),
  ('arboliva_seed_sower_balance', 3, 'Archaludon', 'Metal Coat', 'Stamina', 'Modest', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Electro Shot","Flash Cannon","Body Press","Protect"]'::jsonb, NULL, 'Special Breaker'),
  ('arboliva_seed_sower_balance', 4, 'Gholdengo', 'Spell Tag', 'Good as Gold', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Make It Rain","Shadow Ball","Nasty Plot","Protect"]'::jsonb, NULL, 'Special Cleaner'),
  ('arboliva_seed_sower_balance', 5, 'Garchomp', 'Soft Sand', 'Rough Skin', 'Jolly', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Earthquake","Dragon Claw","Rock Slide","Protect"]'::jsonb, NULL, 'Fast Physical Pressure'),
  ('arboliva_seed_sower_balance', 6, 'Amoonguss', 'Lum Berry', 'Regenerator', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Spore","Rage Powder","Pollen Puff","Protect"]'::jsonb, NULL, 'Disruption / Sustain');

-- pelipper_basculegion_rain
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('pelipper_basculegion_rain', 1, 'Pelipper', 'Focus Sash', 'Drizzle', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Tailwind","Hurricane","Weather Ball","Protect"]'::jsonb, NULL, 'Rain / Speed Control'),
  ('pelipper_basculegion_rain', 2, 'Basculegion', 'Mystic Water', 'Swift Swim', 'Adamant', 50, '{"atk":32,"def":0,"hp":2,"spa":0,"spd":0,"spe":32}'::jsonb, '["Wave Crash","Aqua Jet","Crunch","Protect"]'::jsonb, NULL, 'Rain Sweeper'),
  ('pelipper_basculegion_rain', 3, 'Rillaboom', 'Miracle Seed', 'Grassy Surge', 'Adamant', 50, '{"atk":32,"def":0,"hp":32,"spa":0,"spd":2,"spe":0}'::jsonb, '["Grassy Glide","Wood Hammer","Knock Off","U-turn"]'::jsonb, NULL, 'Terrain Pivot'),
  ('pelipper_basculegion_rain', 4, 'Gholdengo', 'Spell Tag', 'Good as Gold', 'Timid', 50, '{"atk":0,"def":0,"hp":2,"spa":32,"spd":0,"spe":32}'::jsonb, '["Make It Rain","Shadow Ball","Nasty Plot","Protect"]'::jsonb, NULL, 'Special Cleaner'),
  ('pelipper_basculegion_rain', 5, 'Archaludon', 'Metal Coat', 'Stamina', 'Modest', 50, '{"atk":0,"def":2,"hp":32,"spa":32,"spd":0,"spe":0}'::jsonb, '["Electro Shot","Flash Cannon","Body Press","Protect"]'::jsonb, NULL, 'Rain Breaker'),
  ('pelipper_basculegion_rain', 6, 'Amoonguss', 'Sitrus Berry', 'Regenerator', 'Calm', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":32,"spe":0}'::jsonb, '["Spore","Rage Powder","Pollen Puff","Protect"]'::jsonb, NULL, 'Disruption / Sustain');

-- kevin_meta_sun
INSERT INTO team_members (team_id, slot, species, item, ability, nature, level, evs, moves, tera_type, role_tag) VALUES
  ('kevin_meta_sun', 1, 'Charizard', 'Charizardite Y', 'Solar Power', 'Timid', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":1,"spe":32}'::jsonb, '["Heat Wave","Solar Beam","Weather Ball","Protect"]'::jsonb, NULL, 'Primary Sun Breaker'),
  ('kevin_meta_sun', 2, 'Venusaur', 'Focus Sash', 'Chlorophyll', 'Modest', 50, '{"atk":0,"def":0,"hp":1,"spa":32,"spd":1,"spe":32}'::jsonb, '["Sleep Powder","Leaf Storm","Sludge Bomb","Protect"]'::jsonb, NULL, 'Sun Speed Control / Sleep Pressure'),
  ('kevin_meta_sun', 3, 'Garchomp', 'Choice Scarf', 'Rough Skin', 'Adamant', 50, '{"atk":32,"def":1,"hp":1,"spa":0,"spd":0,"spe":32}'::jsonb, '["Rock Slide","Dragon Claw","Earthquake","Bulldoze"]'::jsonb, NULL, 'Fast Spread Pressure'),
  ('kevin_meta_sun', 4, 'Sneasler', 'White Herb', 'Unburden', 'Jolly', 50, '{"atk":32,"def":0,"hp":0,"spa":0,"spd":0,"spe":32}'::jsonb, '["Dire Claw","Close Combat","Rock Slide","Coaching"]'::jsonb, NULL, 'Fast Disruption / Cleanup'),
  ('kevin_meta_sun', 5, 'Incineroar', 'Sitrus Berry', 'Intimidate', 'Adamant', 50, '{"atk":32,"def":0,"hp":32,"spa":0,"spd":0,"spe":2}'::jsonb, '["Darkest Lariat","Flare Blitz","Fake Out","Knock Off"]'::jsonb, NULL, 'Pivot / Tempo Control'),
  ('kevin_meta_sun', 6, 'Whimsicott', 'Mental Herb', 'Prankster', 'Timid', 50, '{"atk":0,"def":2,"hp":32,"spa":0,"spd":0,"spe":32}'::jsonb, '["Tailwind","Encore","Moonblast","Protect"]'::jsonb, NULL, 'Speed Control / Disruption');

COMMIT;
