// Project Roadmap tab should track shipped work, validation, gaps, and milestones.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(ROOT, 'style.css'), 'utf8');
const ui = fs.readFileSync(path.join(ROOT, 'ui.js'), 'utf8');

let pass = 0;
let fail = 0;
function T(name, fn) {
  try { fn(); console.log('  PASS', name); pass++; }
  catch (e) { console.log('  FAIL', name, '-', e.message); fail++; }
}
function inc(hay, needle, msg='') {
  if (String(hay).indexOf(needle) < 0) throw new Error((msg || 'missing') + ': ' + needle);
}

console.log('\n=== project roadmap tab tests ===\n');

T('1. Roadmap is a top-level tab and mobile picker option', () => {
  inc(html, 'data-tab="home">Home');
  inc(html, '<option value="home">Home</option>');
  inc(html, '<section class="tab-panel active" id="tab-home">');
  inc(html, 'id="team-lab-home-hub"');
  inc(html, 'data-tab="overview">Roadmap');
  inc(html, '<option value="overview">Roadmap</option>');
  inc(html, '<section class="tab-panel" id="tab-overview">');
  inc(html, 'id="overview-content"');
  inc(html, '<h2 class="section-title">Roadmap</h2>');
  inc(html, '<section class="tab-panel" id="tab-simulator">');
});

T('2. Overview tracks accomplished work and validation proof', () => {
  inc(ui, 'CS_OVERVIEW_DATA');
  inc(ui, 'Current Truth');
  inc(ui, 'Not 100% yet');
  inc(ui, 'Damage Logs');
  inc(ui, 'Applied/calc split fixed locally');
  inc(ui, 'Testing Catalog Target');
  inc(ui, 'Top 10 Champion archetypes');
  inc(ui, 'Removed Teams');
  inc(ui, '17 legacy/inferred rows');
  inc(ui, '15 approved runtime rows');
  inc(ui, 'Stress Lite totals + coaching summary live');
  inc(ui, 'DB Log Detail');
  inc(ui, 'Summary/capped; exports are forensic proof');
  inc(ui, 'Current Champion source sweep recorded');
  inc(ui, 'Sim Truth Gate');
  inc(ui, 'Knock Off');
  inc(ui, 'Verified');
  inc(ui, 'Move Support');
  inc(ui, '120 verified / 0 baseline');
  inc(ui, 'Showdown Oracle');
  inc(ui, '56/56 green');
  inc(ui, 'Review tab restored');
  inc(ui, 'Live team-load simulation failure fixed');
  inc(ui, 'Lethal Sitrus and Oran timing fixed');
  inc(ui, 'Champion item and SP gate added');
  inc(ui, 'Stable Pokemon identity in sim exports');
  inc(ui, 'Move priority aligned with Showdown data');
  inc(ui, 'Showdown primary move metadata for imported teams');
  inc(ui, 'Target category bridge and stale-target retargeting guarded');
  inc(ui, 'Runtime naming cheat sheet added');
  inc(ui, 'Large-run QA artifact export added');
  inc(ui, 'QA coverage summary added to exports');
  inc(ui, 'Recoil applied HP evidence corrected');
  inc(ui, 'Type multiplier audit added');
  inc(ui, 'Low Kick weight source added');
  inc(ui, 'Core shipped move parity closed');
  inc(ui, 'Typed held-item damage boosts fixed');
  inc(ui, 'Stat and effective-speed evidence added to exports');
  inc(ui, 'Knock Off item behavior guarded');
  inc(ui, 'Champions SP/SV stat format');
  inc(ui, 'damage_events');
  inc(ui, 'effect_events');
  inc(ui, 'qa_coverage_summary');
  inc(ui, 'Effect math evidence added to turn logs');
  inc(ui, 'Shed Tail now follows Showdown context: 1/2 max HP cost rounded up');
  inc(ui, 'Architecture and evidence map added');
  inc(ui, 'source-to-engine-to-export map');
  inc(ui, 'DB history limits');
  inc(ui, 'Showdown sync and DB writer staged');
  inc(ui, 'Curated ability inventory modeled');
  inc(ui, 'Simulation-first direction documented');
  inc(ui, 'Public release milestone map documented');
  inc(ui, 'Live exported logs prove the sim now runs');
  inc(ui, 'Latest v2.1.33 logs pass strict structure and expose stacked mechanics evidence');
  inc(ui, 'The only no-valid-target line is terminal after the player side is empty');
  inc(ui, 'Item timing regression reproduced and covered');
  inc(ui, 'Fresh logs exposed a targeting boundary bug');
  inc(ui, 'Ability coverage guard is green');
  inc(ui, 'Priority-suppression family now has same-rule regression proof');
  inc(ui, 'Armor Tail, Dazzling, and Queenly Majesty');
  inc(ui, 'Previous v2.1.36 release checks were green');
  inc(ui, 'The current local damage-log and approved-team-gate slice has focused green checks');
  inc(ui, 'Damage applied versus calculated logging fixed locally');
  inc(ui, 'Strategy Priority Board added');
  inc(ui, 'coach call first');
  inc(ui, 'Branch move coach feeds the Strategy guide');
  inc(ui, 'confidence-rated avoid moves');
  inc(ui, 'Approved Champion team lane guarded');
  inc(ui, 'DB species/move legality view added');
  inc(ui, 'Showdown sync approval guard tightened');
  inc(ui, 'Low Kick weight-based damage matches Showdown');
  inc(ui, 'Showdown data/moves.ts records Low Kick basePower as 0');
  inc(ui, '100% Champion parity checklist is explicit');
  inc(ui, 'Damage stack oracle is green');
  inc(ui, 'Tera Blast parity is isolated from current Reg M-A');
  inc(ui, 'Knock Off source-truth behavior is documented');
  inc(ui, 'Turn-order stack evidence is green');
  inc(ui, 'GitHub issue sweep completed');
  inc(ui, 'Previous Y/Alfredo source sync completed');
});

T('3. Overview names current Supabase and Showdown DB alignment state', () => {
  inc(ui, 'Supabase app wiring is live for existing app tables');
  inc(ui, 'Local DB contract suite is green');
  inc(ui, 'Latest v2.1.42 browser logs validate and expose effect evidence');
  inc(ui, 'Fresh v2.1.43 single logs exposed recoil evidence naming drift');
  inc(ui, 'Live Supabase freshness checks require `RUN_LIVE_DB=1`');
  inc(ui, 'overview-showdown-db-inspect');
  inc(ui, 'loadShowdownDbSnapshot');
  inc(ui, 'loadShowdownEntities');
  inc(ui, 'approvedCounts');
  inc(ui, 'sourceFiles');
  inc(ui, 'Champions override seed/review remains open');
  inc(ui, 'generate_showdown_data.mjs');
  inc(ui, 'Live logs exposed stale DB item drift');
  inc(ui, 'Pokemon data audit has unresolved reviewer risk');
  inc(ui, '100% parity still has non-move gates');
  inc(ui, 'Mechanics truth beta gate remains open');
  inc(ui, 'Move support is 120 verified / 0 baseline / 0 incomplete');
  inc(ui, 'Source refresh needed must be visible before trust claims');
  inc(ui, 'Full raw thousand-battle retention is still not automatic');
  inc(ui, 'Supabase history is not full forensic turn-log storage yet');
  inc(ui, 'downloaded turn-log JSON and QA Artifact export');
  inc(ui, 'Team editor is guarded but not a fluid full builder yet');
  inc(ui, 'Alfredo #241');
  inc(ui, 'Life Orb');
  inc(ui, 'showdown_sync_runs');
  inc(ui, 'showdown_entities');
  inc(ui, 'champions_overrides');
});

T('3b. replay formatter accepts richer applied damage log brackets', () => {
  inc(ui, 'dmg(?:,[^\\]]*)?');
  inc(ui, 'lost $1 HP');
});

T('4. Overview includes next milestones and source docs', () => {
  inc(ui, 'Stress-test, rebuild, and prove the new truth board');
  inc(ui, 'Replace removed teams with approved Champion teams');
  inc(ui, 'Trick Room, anti-Trick Room, Tailwind/speed, sun, rain, sand or snow');
  inc(ui, 'Verify the next deployed source URL and QA artifact');
  inc(ui, 'Mirror or update JD issue alignment in the Y fork');
  inc(ui, 'Apply Champion item cleanup to live Supabase rows');
  inc(ui, 'Seed and review Champions overrides');
  inc(ui, 'Design DB forensic log retention before relying on saved history');
  inc(ui, 'build_id, source_url, and retention metadata');
  inc(ui, 'Prove post-move mechanics by battle system');
  inc(ui, 'With the shipped move audit at 120 verified / 0 baseline / 0 incomplete');
  inc(ui, 'Close the mechanics truth beta gate');
  inc(ui, 'Pokemon Champions mechanics truth gate');
  inc(ui, 'finish action-denial and priority-suppression reason inventory for singles and doubles');
  inc(ui, 'Make replay and QA transparency strong enough for coaching trust');
  inc(ui, 'HP-loss causes, and move-failure causes obvious enough');
  inc(ui, 'Rebuild editor into full Champion team builder');
  inc(ui, 'Keep Alfredo and Y fork synced through protected PRs');
  inc(ui, 'Surface source drift as update needed in Overview');
  inc(ui, 'Recent Fix + Issue Snapshot');
  inc(ui, 'recent-fixes-and-open-issues-2026-06-21.md');
  inc(ui, 'Architecture + Evidence Map');
  inc(ui, 'CHAMPION_SIM_ARCHITECTURE_AND_EVIDENCE.md');
  inc(ui, 'Release Discipline + Cleanup Gates');
  inc(ui, 'RELEASE_DISCIPLINE_AND_CLEANUP_GATES.md');
  inc(ui, 'Active Slice Closeout Status');
  inc(ui, 'ACTIVE_SLICE_CLOSEOUT_STATUS.md');
  inc(ui, 'Legality 99 Target Plan');
  inc(ui, 'LEGALITY_99_TARGET_PLAN.md');
  inc(ui, 'Champion Parity 100 Checklist');
  inc(ui, 'champion_parity_100_checklist.md');
  inc(ui, 'Move Mechanics QA Closeout Plan');
  inc(ui, 'MOVE_MECHANICS_QA_CLOSEOUT_PLAN.md');
  inc(ui, 'Move Support Audit');
  inc(ui, 'move_support_audit.md');
  inc(ui, 'Type Multiplier Audit');
  inc(ui, 'type_multiplier_audit.md');
  inc(ui, 'Simulation First');
  inc(ui, 'SIMULATION_FIRST_REALIGNMENT_2026-06-06.md');
  inc(ui, 'Public Release Plan');
  inc(ui, 'PUBLIC_RELEASE_MILESTONE_PLAN_2026-06-06.md');
  inc(ui, 'Showdown DB Stress Test');
  inc(ui, 'SHOWDOWN_DB_WIRING_STRESS_TEST_2026-06-06.md');
  inc(ui, 'Jdoutt38 Investigation');
  inc(ui, 'JDOUTT38_INVESTIGATION_2026-06-06.md');
  inc(ui, 'Closure Confidence');
  inc(ui, 'CLOSURE_CONFIDENCE_2026-06-06.md');
  inc(ui, 'Repo Parity Report');
  inc(ui, 'REPO_PARITY_REPORT_2026-06-06.md');
  inc(ui, 'Closeout Note');
  inc(ui, 'CLOSEOUT_2026-06-06.md');
  inc(ui, 'Showdown DB Plan');
  inc(ui, 'SHOWDOWN_DB_SOURCE_OF_TRUTH_PLAN.md');
  inc(ui, 'Mechanics Truth Beta Gate Checklist');
  inc(ui, 'mechanics_truth_beta_gate_checklist.md');
  inc(ui, 'Approved Runtime Team Test Matrix');
  inc(ui, 'approved_runtime_team_test_matrix.md');
  inc(ui, 'Runtime Naming Cheat Sheet');
  inc(ui, 'SHOWDOWN_RUNTIME_NAMING_CHEATSHEET.md');
  inc(ui, 'SHOWDOWN_SYNC_ARCHITECTURE.md');
});

T('4b. Architecture evidence map documents the QA proof contract', () => {
  const doc = fs.readFileSync(path.join(ROOT, 'docs', 'CHAMPION_SIM_ARCHITECTURE_AND_EVIDENCE.md'), 'utf8');
  inc(doc, 'Source truth');
  inc(doc, 'Review and approval layer');
  inc(doc, 'Generated runtime assets');
  inc(doc, 'Deterministic engine');
  inc(doc, 'QA evidence outputs');
  inc(doc, 'Supabase Boundary');
  inc(doc, 'Damage Calculation Evidence');
  inc(doc, 'Effect Evidence');
  inc(doc, 'Shed Tail has two different HP values');
  inc(doc, 'Required QA Proof Workflow');
  inc(doc, 'Current Non-100% Gaps');
  inc(doc, 'v2.2.90-qa-slice-readout');
  inc(doc, 'Current Evidence QA');
  inc(doc, 'Release Matrix QA');
  inc(doc, 'Device-Safe Stress QA');
  inc(doc, 'Tactical Coaching QA');
  inc(doc, 'No QA artifact may be used as complete Champion legality');
  const cleanup = fs.readFileSync(path.join(ROOT, 'docs', 'RELEASE_DISCIPLINE_AND_CLEANUP_GATES.md'), 'utf8');
  inc(cleanup, '99% closed');
  inc(cleanup, '100% closed');
  inc(cleanup, 'What exact problem did this solve?');
  inc(cleanup, 'Which QA slice proves it?');
  inc(cleanup, 'Do not leave it implicit in chat.');
  inc(cleanup, 'UI/runtime modularization pressure');
  inc(cleanup, 'News Feed Sync versus feature-release races');
  inc(cleanup, 'do not hand-edit the bundle');
  inc(cleanup, 'rerun `python3 poke-sim/tools/build-bundle.py`');
  inc(cleanup, 'scheduled source/news sync should use a branch or PR');
  const closeout = fs.readFileSync(path.join(ROOT, 'docs', 'ACTIVE_SLICE_CLOSEOUT_STATUS.md'), 'utf8');
  inc(closeout, '100% closed');
  inc(closeout, '99% closed');
  inc(closeout, 'open blocker');
  inc(closeout, 'No active strategic slice should be marked `100% closed` today.');
  inc(closeout, 'QA slice naming and claim review');
  inc(closeout, 'Full Pokemon Champions legality / Regulation M-B runtime promotion');
  inc(closeout, 'Battle Sensei true coaching brain');
  inc(closeout, 'GitHub generated-artifact release hygiene');
  inc(closeout, 'News Feed Sync versus feature-release conflict path');
  inc(closeout, 'UI/runtime modularization');
  inc(closeout, 'Fresh live proof attached on 2026-07-01');
  inc(closeout, 'champions-sim-qa-artifact-2026-07-01T14-02-36.json');
  inc(closeout, 'champions-sim-qa-artifact-2026-07-01T14-03-05.json');
  inc(closeout, 'qa_dashboard.claim_boundary');
  inc(closeout, 'complete Pokemon Champion legality');
  inc(closeout, 'Trick Room active state');
  inc(closeout, 'non-standard stat-source move traces');
  inc(closeout, 'MOVE_MECHANICS_QA_CLOSEOUT_PLAN.md');
  inc(closeout, 'Live QA closeout must happen by mechanic family');
  inc(closeout, 'replay_logic_audit');
  inc(closeout, 'turn logs, damage rows, move traces, effect rows, faint causes');
  inc(closeout, 'What exact claim did we prove?');
  const moveQa = fs.readFileSync(path.join(ROOT, 'docs', 'MOVE_MECHANICS_QA_CLOSEOUT_PLAN.md'), 'utf8');
  inc(moveQa, 'Move Mechanics QA Closeout Plan');
  inc(moveQa, 'Move registry support');
  inc(moveQa, 'Live mechanic-family proof');
  inc(moveQa, '120 verified / 0 baseline / 0 incomplete');
  inc(moveQa, 'It does not prove every move appeared in fresh live browser QA evidence.');
  inc(moveQa, 'Non-standard stat source');
  inc(moveQa, 'Foul Play, Body Press, Psyshock-style defense targeting');
  inc(moveQa, 'Do not brute-force all legal game trees in the browser.');
  inc(moveQa, 'A move family can be marked `100% closed` only when');
  const legality99 = fs.readFileSync(path.join(ROOT, 'docs', 'LEGALITY_99_TARGET_PLAN.md'), 'utf8');
  inc(legality99, 'Legality 99 Target Plan');
  inc(legality99, 'true 99% legality');
  inc(legality99, '`100% legality` requires complete official or in-game verified proof');
  inc(legality99, 'unknown Champion legality returns `needs_verification`, never `verified`');
  inc(legality99, 'one known legal team accepted by Pokemon Champions');
  inc(legality99, 'one known illegal team rejected by Pokemon Champions');
  inc(legality99, 'stale ruleset');
  inc(legality99, 'Team Lab/global rankings cannot use `needs_verification` teams in official scopes');
  inc(closeout, 'LEGALITY_99_TARGET_PLAN.md');
  inc(closeout, 'true 99% legality');
  inc(closeout, 'Build the Regulation M-B legality evidence package');
});

T('5. Overview styles are responsive and scan-friendly', () => {
  inc(css, '.overview-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--sp3)}');
  inc(css, '.overview-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(300px,.8fr);gap:var(--sp4);align-items:start}');
  inc(css, '.overview-db-inspector');
  inc(css, '.overview-milestone-board');
  inc(css, '.overview-milestone-summary');
  inc(css, '.overview-bucket');
  inc(css, '.overview-closed-proof-archive');
  inc(css, '.overview-qa-josh-issues');
  inc(css, '.team-lab-newsroom');
  inc(css, '.team-lab-gates');
  inc(css, '.team-lab-gate-grid');
  inc(css, '.team-lab-gate-actions');
  inc(css, '.team-lab-admin-controls');
  inc(css, '.team-lab-admin-reason');
  inc(css, '.team-lab-admin-status');
  inc(css, '.home-landing-hero');
  inc(css, 'font-size:clamp(44px,7.2vw,92px)');
  inc(css, '.home-landing-hero h2:after');
  inc(css, 'linear-gradient(90deg,var(--blue),var(--green),var(--gold))');
  inc(css, '.home-landing-chips');
  inc(css, '.home-value-strip');
  inc(css, '.home-landing-chips span{display:inline-flex;align-items:center;min-height:30px');
  inc(css, '.home-landing-proof span{font-family:var(--font-mono);font-size:11px');
  inc(css, '.home-value-strip p{color:var(--text-m);font-size:15px');
  inc(css, '.home-start-rail');
  inc(css, '.pokemon-news-headlines');
  inc(css, '.home-proof-snapshot');
  inc(css, '.home-sim-preview');
  inc(css, '.home-sim-output-card');
  inc(css, '.home-start-cycle');
  inc(css, '.home-start-steps');
  inc(css, '.home-trust-strip');
  inc(css, '.pokemon-news-feed');
  inc(css, '.pokemon-news-slide.active');
  inc(css, '.team-lab-top25-table');
  inc(css, '.overview-db-counts');
  inc(css, '.overview-db-table');
  inc(css, '.overview-status.done');
  inc(css, '.overview-status.gap');
  inc(css, '@media(max-width:900px){.overview-grid{grid-template-columns:1fr}.overview-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.overview-db-summary,.overview-db-counts{grid-template-columns:repeat(2,minmax(0,1fr))}.home-landing-hero,.home-sim-preview,.home-quick-plan,.team-lab-hero,.home-proof-snapshot{grid-template-columns:1fr}.home-trust-strip{grid-template-columns:1fr}.team-lab-hero-badges{justify-content:flex-start}}');
  inc(css, '@media(max-width:720px){.pokemon-news-slide.active{grid-template-columns:1fr}.pokemon-news-slides{min-height:0}.pokemon-news-image-link,.pokemon-news-image-link img{min-height:190px}}');
});

T('6. Overview renders through a reusable function for future growth', () => {
  inc(ui, 'function renderOverviewTab()');
  inc(ui, 'csBuildOverviewMilestones');
  inc(ui, 'overview-milestone-board');
  inc(ui, 'Milestone Board');
  inc(ui, 'Done / Open / Next');
  inc(ui, 'function csRenderOverviewClosedProofArchive');
  inc(ui, 'overview-closed-proof-summary');
  inc(ui, 'Validated proof stays available for audit');
  inc(ui, 'Simulation Truth & Mechanics Accuracy');
  inc(ui, 'Source Truth, Regulations & Data Governance');
  inc(ui, 'Team Lab, Saved Teams & Evidence Pipeline');
  inc(ui, 'Release Reliability, Security & Repo Sync');
  inc(ui, 'Coaching, UX & Player Learning');
  inc(ui, 'Repo Docs Guide');
  inc(ui, 'what to read first');
  inc(ui, 'QA / Josh Review Issues');
  inc(ui, 'Josh review: Pokemon data audit workbook (#123)');
  inc(ui, 'Manual QA: Champion Replay Intelligence smoke test (#105)');
  inc(ui, 'Second verified Champion replay artifact (#104)');
  inc(ui, 'Mechanics truth audit beta gate (#149)');
  inc(ui, 'Team Lab / Leaderboard Plan');
  inc(ui, 'function csRenderTeamLabNewsroomHub');
  inc(ui, 'function renderTeamLabHomeHub');
  inc(ui, 'Battle Labs');
  inc(ui, 'Start Simulating');
  inc(ui, 'Build stronger teams by testing real matchups, reading the swing turn, and changing one thing with proof.');
  inc(ui, 'Champion rules guarded');
  inc(ui, 'Which lead, four, move, or switch gives me the best line?');
  inc(ui, 'Sim the matchup');
  inc(ui, 'Review the battle');
  inc(ui, 'Improve cleanly');
  inc(ui, 'function csRenderHomeStartRail');
  inc(ui, 'Start with one decision.');
  inc(ui, 'function csRenderHomeProofSnapshot');
  inc(ui, '39 real-battle files ingested');
  inc(ui, 'Top 25 is locked until enough verified simulator evidence exists.');
  inc(ui, 'pokemon-news-headline');
  inc(ui, 'Source-backed news watch');
  inc(ui, 'Official source watch');
  inc(ui, 'Release status');
  inc(ui, 'See the battle like a coach would.');
  inc(ui, 'Rain Balance vs Speed Control');
  inc(ui, 'The 4-step testing cycle');
  inc(ui, 'Choose or import a team');
  inc(ui, 'Run the matchup');
  inc(ui, 'Read the swing turn');
  inc(ui, 'Change one thing and rerun');
  inc(ui, 'Evidence-bound rankings');
  inc(ui, 'Replay-verifiable coaching');
  inc(ui, 'function csRenderHomeStartCycle');
  inc(ui, 'function csRenderHomeSimPreview');
  inc(ui, 'function csInitHomeTabActions');
  inc(ui, 'function csPokemonNewsFeedItems');
  inc(ui, 'function csInitPokemonNewsCarousel');
  inc(ui, 'assets/news-card.svg');
  inc(ui, 'Source-backed news watch');
  inc(ui, 'Article thumbnails come from approved feed metadata when available.');
  inc(ui, 'Official source watch');
  inc(ui, 'Pokemon Champions Official Source Hub');
  inc(ui, 'Evidence-First Rankings Stay Gated');
  inc(ui, 'data-news-fallback-src');
  inc(ui, "addEventListener('error'");
  inc(ui, 'Top 25 waits for proof');
  inc(ui, 'Experimental rows are visible. Official rankings still require verified legality and promotion rules.');
  inc(ui, 'function csTeamLabRankingGates');
  inc(ui, 'function csRenderTeamLabRankingGates');
  inc(ui, 'function csRenderTeamLabAdminControls');
  inc(ui, 'function csInitTeamLabAdminControls');
  inc(ui, 'function csBuildTeamLabLocalTop25Rows');
  inc(ui, 'function csBuildTeamLabDbBranchTop25Rows');
  inc(ui, 'function csRefreshTeamLabDbBranchPreview');
  inc(ui, 'loadBranchCoverageSummary({ limit: 2500 })');
  inc(ui, 'Saved branch rows - not official global rank');
  inc(ui, 'TEAM_LAB_TEAM_ID_MAPPING_UNVERIFIED');
  inc(ui, 'function csTeamLabLocalResetTimestamp');
  inc(ui, 'data-team-lab-top25-body');
  inc(ui, 'Ranking trust gates');
  inc(ui, 'Top teams stay locked until the evidence is safe.');
  inc(ui, 'Validated teams');
  inc(ui, 'Replay-backed sim evidence');
  inc(ui, 'Trusted import worker');
  inc(ui, 'Promotion rules');
  inc(ui, 'Generate sim evidence');
  inc(ui, 'Review replay proof');
  inc(ui, 'Team Lab leaderboard');
  inc(ui, 'Score');
  inc(ui, 'Quality');
  inc(ui, 'Admin QA controls');
  inc(ui, 'Reset local QA rankings');
  inc(ui, 'team_lab:qa_reset_at');
  inc(ui, 'Shared/global rankings unchanged until trusted admin reset runs.');
  inc(ui, 'Latest Champion Updates');
  inc(ui, 'function csRenderSourceRegistry');
  inc(ui, 'Sources used to build the sim');
  inc(ui, 'CHAMPIONS_SOURCE_REGISTRY');
  inc(ui, 'Source tier');
  inc(ui, 'Do not use for:');
  inc(ui, 'needs_verification');
  inc(ui, 'Pokemon Champions Is Available Now on iOS and Android Devices');
  inc(ui, 'Regulation Set M-B Kicks off a New Ranked Battles Season');
  inc(ui, 'Pokemon Champions Monthly Challenge Series June 2026');
  inc(ui, 'Relive the Eras of Pokemon VGC');
  inc(ui, 'data-news-slide');
  inc(ui, 'Top 25 Simulator Teams');
  inc(ui, 'No fake rankings');
  inc(ui, 'local QA preview');
  inc(ui, 'Local only - not official global rank');
  inc(ui, 'Locked until proven');
  inc(ui, 'Team Lab read UI (#179)');
  inc(ui, 'Custom team submission and validation (#180)');
  inc(ui, 'Leaderboard recalculation and stale guards (#181)');
  inc(ui, 'QA artifact import pipeline (#182)');
  inc(ui, 'Compare My Team matchup matrix (#183)');
  inc(ui, 'Hidden-details privacy and public API contract (#184)');
  inc(ui, 'Account profile analytics (#185)');
  inc(ui, 'Global vs personal analytics boundary');
  inc(ui, 'Canonical Team Lab trust roadmap');
  inc(ui, '99% versus 100% closeout');
  inc(ui, 'Closeout discipline before new work');
  inc(ui, 'Active slice closeout map added');
  inc(ui, 'Fresh live closeout QA artifacts recorded');
  inc(ui, 'Move mechanics QA closeout plan added');
  inc(ui, 'GitHub generated-artifact release guard documented');
  inc(ui, 'Move scheduled source/news sync to branch or PR mode');
  inc(ui, 'regenerate pokemon-champion-2026.html and generated/release_artifact.json');
  inc(ui, 'Legality evidence package foundation added');
  inc(ui, 'legality_evidence_package.js');
  inc(ui, 'trusted source captures');
  inc(ui, 'promotion readiness');
  inc(ui, 'Legality 99 target plan added');
  inc(ui, 'Build Regulation M-B legality evidence package');
  inc(ui, 'source-backed active regulation package');
  inc(ui, 'known legal/illegal fixtures');
  inc(ui, 'stale ruleset guards');
  inc(ui, 'Active legality source package gate');
  inc(ui, 'canonical for legality closeout');
  inc(ui, 'Replay logic QA audit added');
  inc(ui, 'replay_logic_audit to QA artifacts');
  inc(ui, 'Replay Logic QA dashboard lane');
  inc(ui, 'damage_events, move_rule_trace rows, effect_events');
  inc(ui, 'shipped move registry coverage plus live mechanic-family proof');
  inc(ui, 'Run non-standard stat-source targeted proof first');
  inc(ui, 'nonstandard_stat_source_trace, foul_play_trace, body_press_trace, psyshock_trace');
  inc(ui, 'All-move QA boundary and targeted proof plan');
  inc(ui, 'canonical for move QA closeout');
  inc(ui, 'Tactical Sweep and Stress Lite exports both captured build_id, source_url, qa_claim_review');
  inc(ui, 'full Champion legality, complete mechanics coverage, and official/global rankings out of scope');
  inc(ui, '100% closed, 99% closed with named residual risk, open blocker, or next priority');
  inc(ui, 'Use the active slice closeout map before starting new work');
  inc(ui, 'QA naming, release cleanup, replay claim audit, Team Lab preview, home page, and replay intake are 99% closed');
  inc(ui, 'Current 99% / 100% / blocker map');
  inc(ui, 'canonical for active closeout');
  inc(ui, 'ChampionsSim.overview');
  inc(ui, 'renderTeamLabHomeHub();');
  inc(ui, 'renderOverviewTab();');
  inc(ui, '.tab-btn[data-tab="overview"]');
});

console.log(`\nproject roadmap tab: ${pass} pass, ${fail} fail\n`);
process.exit(fail ? 1 : 0);
